export default (t: Function) => [
  {
    headerCheckboxSelection: true,
    checkboxSelection: true,
    showDisabledCheckboxes: true,
    filter: false,
    width: 55,
    editable: false,
    minWidth: 55,
  },
  {
    field: 'ip',
    headerName: t('ip'),
    flex: 1,
    headerClass: 'ag-right-aligned-header',
    cellStyle: { textAlign: 'right' },
    cellClass: 'ag-right-aligned-cell',
  },
  {
    field: 'userAgent',
    headerName: t('userAgent'),
    flex: 1,
  },
  {
    field: 'signedInDateTime',
    headerName: t('lastSignIn'),
    flex: 1,
    headerClass: 'ag-right-aligned-header',
    cellStyle: { textAlign: 'right' },
    cellClass: 'ag-right-aligned-cell',
  },
  {
    field: 'verified',
    headerName: t('verifiedDevice'),
    width: 160,
    cellRenderer: 'VerifyStatusRenderer',
    headerClass: 'centered',
    cellStyle: { display: 'flex', justifyContent: 'center', alignItems: 'center' },
  },
  {
    field: 'status',
    headerName: t('deviceStatus'),
    headerClass: 'centered',
    cellStyle: { display: 'flex', justifyContent: 'center', alignItems: 'center' },
    flex: 1,
    minWidth: 120,
    cellRenderer: 'DeviceStatusRenderer',
  },
];
