export const de = {
  ownedLicences: 'Liste der autorisierten Lizenzen',
  ownedLicencesDescription:
    'Zugriff auf andere Systemanwendungen können Sie vom Softwareanbieter erhalten',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Name',
  changePassword: 'Passwort ändern',
  editPersonalDetails: 'Persönliche Daten bearbeiten',
  oldPassword: 'Altes Passwort',
  unlockAccount: 'Konto entsperren',
  newPassword: 'Neues Passwort',
  confirmNewPassword: 'Neues Passwort bestätigen',
  reNewPassword: 'Neues Passwort bestätigen',
  accountBlocked: 'Konto wurde gesperrt',
  firstName: 'Vorname',
  lastName: 'Nachname',
  language: 'Sprache',
  blockAccount: 'Konto sperren',
  personalId: 'Pesel',
  email: 'E-Mail',
  personalPhone: 'Private Telefonnummer',
  city: 'Stadt',
  postCode: 'Postleitzahl',
  description: 'Beschreibung',
  address: 'Adresse',
  noNotifications: 'Keine Benachrichtigungen',
  'Welcome to': 'Willkommen bei',
  'Empower your company with the best solutions':
    'Stärken Sie Ihr Unternehmen mit den besten Lösungen',
  notifications: 'Benachrichtigungen',
  companyNip: 'NIP',
  'Distribution, Access, and Integration System': 'Verteilungs-, Zugriffs- und Integrationssystem',
  'System for Employment & Recruitment Agencies':
    'System für Arbeits- und Personalvermittlungsagenturen',
  'Pawn shop system & micro warehouse distribution':
    'System für Pfandhäuser und Mikrolagervertrieb',
  'QUARX Manager': 'QUARX Manager',
  more: 'Mehr',
  'Secure Authorization System for Your Solutions':
    'Sicheres Autorisierungssystem für Ihre Lösungen',
  submit: 'Bestätigen',
  companyName: 'Firmenname',
  dashboard: 'Dashboard',
  companyAddress: 'Firmenadresse',
  'Page Size:': 'Seitengröße:',
  pageSizeSelectorLabel: 'Seitengröße',
  dashboardDescription: 'Übersicht der Änderungen, allgemeine Statistik',
  host: 'Host',
  authorize: 'Autorisieren',
  licenceUserQty: 'Maximale Anzahl lizenzierter Benutzer',
  newVerificationEmailHasBeenSent: 'Neue Bestätigungs-E-Mail wurde gesendet',
  software: 'Software',
  licenceStart: 'Lizenzbeginn',
  licenceEnd: 'Lizenzende',
  companyPhone: 'Firmentelefon',
  usersSecurity: 'Übersicht',
  services: 'Dienste',
  youCanAuthorizeFromHere: 'Sie können sich von hier aus autorisieren',
  emailTaken: 'E-Mail bereits vergeben',
  website: 'Webseite',
  search: 'Suchen',
  notifyUser: 'Benutzer benachrichtigen',
  sendNotification: 'Benachrichtigung senden',
  send: 'Senden',
  receivers: 'Empfänger',
  devicesOnline: 'Geräte online',
  noSelectedUsers: 'Keine ausgewählten Empfänger',
  title: 'Titel',
  code: 'Code',
  'title-code': 'Titel (Code)',
  pleaseChooseReceiver: 'Wählen Sie Benutzer, um Empfänger auszuwählen',
  close: 'Schließen',
  saveChanges: 'Änderungen speichern',
  id: 'ID-Nummer',
  usersSecuritySettingsLevel: 'Sicherheitsstufe',
  verified: 'Verifiziert',
  actions: 'Aktionen',
  successfullySent: 'Erfolgreich gesendet',
  successfullySentDescription: 'Benachrichtigung wurde erfolgreich gesendet',
  selected: 'Ausgewählt',
  devices: 'Geräte',
  networks: 'Netzwerke',
  blockIpAddress: 'IP-Adresse sperren',
  blockDevice: 'Gerät sperren',
  serverDown: 'Server nicht erreichbar',
  'Network error': 'Netzwerkfehler',
  unlockIpAddress: 'IP-Adresse entsperren',
  saveNewUser: 'Speichern',
  unlockDevice: 'Gerät entsperren',
  resetPassword: 'Passwort zurücksetzen',
  editYourAccount: 'Kontoeinstellungen',
  editYourAccountDescription: 'Persönliche Daten, Passwort ändern, Lizenzinformationen',
  info: 'Informationen',
  account: 'Konto',
  available: 'Verfügbar',
  permitted: 'Zugewiesen',
  polish: 'Polnisch',
  english: 'Englisch',
  german: 'Deutsch',
  dutch: 'Niederländisch',
  belongingUsersList: 'Benutzer',
  noLicenceOwned: 'Keine Lizenzen vorhanden',
  create: 'Neu erstellen',
  signedDevices: 'Zugewiesene Geräte',
  signedDevicesDescription: 'Liste der Geräte, auf denen sich der Benutzer anmeldet',
  newDeviceEmailVerification: 'Geräteverifizierung per E-Mail',
  newDeviceEmailVerificationDescription:
    'Aktivieren Sie diese Funktion, um jedes neue Gerät, von dem sich der Benutzer anmeldet, per E-Mail zu bestätigen',
  turnedOn: 'Aktiviert',
  turnedOff: 'Deaktiviert',
  removeSelected: 'Ausgewählte entfernen',
  verifyDevice: 'Gerät verifizieren',
  verifyDeviceAdmin: 'Als verifiziert festlegen',
  profile: 'Profil',
  licences: 'Lizenzen',
  editAccount: 'Einstellungen',
  sessionExpiry: 'Sitzungsdauer (Minuten)',
  validTo: 'Sitzung aktiv bis:',
  refreshIn: 'Aktualisierung in:',
  refreshLocked: 'Deaktiviert',
  sessionExpiryDescription: 'Sie können die standardmäßige Sitzungsdauer verkürzen oder verlängern',
  suppressTokenRefresh: 'Sitzungserneuerung deaktivieren',
  suppressTokenRefreshDescription:
    'Wenn diese Funktion aktiviert ist, wird Ihre Sitzung nach der erforderlichen Zeit nicht erneuert. Dies führt zum Ablauf der Sitzung nach deren Dauer.',
  users: 'Benutzer',
  emailHasBeenChanged: 'E-Mail wurde geändert',
  usersManagement: 'Benutzerverwaltung',
  signOut: 'Abmelden',
  youAreLoggedIn: 'Sie sind eingeloggt.',
  usersManagementDescription: 'Bearbeitung persönlicher Daten, Zugriffskonfiguration',
  manageUsers: 'Verwalten',
  tools: 'Werkzeuge',
  security: 'Sicherheit',
  "The session will refresh upon any activity if the user's online time exceeds":
    'Die Sitzung wird bei jeglicher Aktivität automatisch erneuert, wenn die Online-Zeit des Benutzers überschreitet',
  minutes: 'Minuten',
  'and do not exceeds': 'und nicht überschreitet',
  ip: 'IP',
  userAgent: 'Gerät',
  deviceStatus: 'Gerätestatus',
  verificationLinkHasBeenSentToYourNewAddress:
    'Ein Bestätigungslink wurde an Ihre neue E-Mail-Adresse gesendet',
  off: 'Deaktiviert',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Nutzen Sie den Link, der an die neue Adresse gesendet wurde, oder warten Sie 15 Minuten und versuchen Sie es erneut',
  incorrectPassword: 'Falsches Passwort',
  online: 'Aktiv',
  blockedDevice: 'Gesperrtes Gerät',
  emptyRequiredFields: 'Erforderliche Felder sind leer',
  password: 'Passwort',
  newEmail: 'Neue E-Mail',
  changeEmail: 'E-Mail-Adresse ändern',

  // Fehler
  cannotBanOwnerIpAddress: 'Die aktuelle IP-Adresse kann nicht gesperrt werden',
  youCannotBlockOngoingDevice: 'Das aktuelle Gerät kann nicht gesperrt werden',
  thisDeviceHasBeenBlocked: 'Dieses Gerät wurde gesperrt',
  youMustFillAnEmail: 'Bitte füllen Sie das E-Mail-Feld aus',
  youMustFillAPassword: 'Bitte füllen Sie das Passwort-Feld aus',
  blockedIp: 'Netzwerk gesperrt',
  ipHasBeenBlocked: 'Ihr Netzwerk wurde gesperrt',
  'Request failed with status code 400': 'Fehlerhafte Anfrage',
  'Request failed with status code 303': 'Überprüfung erforderlich',
  userDoesNotBelongToTheAccount: 'Benutzer gehört nicht zu Ihrem Konto',
  deviceDoesNotBelongToTheAccount: 'Gerät gehört nicht zu Ihrem Konto',
  dataInvalidAuthorizationKey: 'Fehler beim Auslesen der Autorisierungsdaten',
  somethingGoneWrong: 'Etwas ist schiefgelaufen',
  noAuthorizationKeyProvided: 'Keine Autorisierungsdaten bereitgestellt',
  userWithThisEmailDoesNotExist: 'Ein Benutzer mit dieser E-Mail-Adresse existiert nicht',
  youNeedToVerifyEmail:
    'Bitte verifizieren Sie Ihre E-Mail. Überprüfen Sie Ihr Postfach oder versuchen Sie es in 15 Minuten erneut',
  incorrectLoginData: 'Falsche Anmeldedaten',
  sessionExpired: 'Sitzung abgelaufen',
  invalidAuthorizationKey: 'Autorisierungsprozess abgelehnt',
  yourResetPasswordHasExpired:
    'Ihre Passwortzurücksetzungssitzung ist abgelaufen. Bitte versuchen Sie es erneut',
  incorrectOldPassword: 'Das alte Passwort ist falsch',
  youMustProvideValidPasswordConfirmation:
    'Sie müssen das Passwort zur Bestätigung korrekt eingeben',
  ' ': ' ',
  Serwisy: 'Dienste',
  youHaveAlreadyVerifiedYourAccount: 'Sie haben Ihr Konto bereits verifiziert',
  userDoesNotExist: 'Benutzer existiert nicht',
  superAdmin: 'Superadministrator',
  admin: 'Administrator',
  user: 'Benutzer',
  'Czas aktywnej sesji (min)': 'Aktive Sitzungsdauer (Minuten)',
  login: 'Einloggen',
  welcome: 'Willkommen',
  'Devices Quantity': 'Gerätemenge',
  'Blocked Devices': 'Gesperrte Geräte',
  'Blocked IPs': 'Gesperrte IPs',
  userIsNotVerified: 'Benutzer ist nicht verifiziert',
  deviceVerified: 'Gerät wurde verifiziert',
  pleaseCheckYourEmailOrRetryAfter15minutes:
    'Bitte überprüfen Sie Ihre E-Mail oder versuchen Sie es in 15 Minuten erneut',
  deviceAlreadyBlocked: 'Gerät ist bereits gesperrt',
  ipAlreadyBlocked: 'IP ist bereits gesperrt',
  updatedUserCouldNotBeFound: 'Aktualisierter Benutzer konnte nicht gefunden werden',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Bitte überprüfen Sie Ihre E-Mail für die Passwortzurücksetzung oder versuchen Sie es in 15 Minuten erneut',
  verificationFailed: 'Verifizierung fehlgeschlagen',
  // Komunikaty
  rowHasBeenUpdated: 'Zeile wurde aktualisiert',
  setNewPassword: 'Neues Passwort festlegen',
  emailsAreEqual: 'E-Mails sind gleich',
  lastSignIn: 'Letzte Anmeldung',
  verifiedDevice: 'Gerät verifiziert',
  yourPasswordHasBeenSuccessfullyChanged: 'Ihr Passwort wurde erfolgreich geändert',
  visitMailBoxAndConfirmPasswordReset:
    'Besuchen Sie Ihr Postfach und bestätigen Sie die Passwortzurücksetzung',
  passwordChanged: 'Passwort geändert',
  passwordHasBeenChanged: 'Passwort wurde geändert',
  passwordHasBeenChangedDescription: 'Ihre Daten wurden geändert',
  confirmationEmailHasBeenSent: 'Bestätigungs-E-Mail wurde gesendet',

  // Ciągi
  _Auth: 'Manager',
  _orizationManager: 'Autorisierung',
  userCreated: 'Benutzer wurde erstellt',
  authorization: 'Autorisierung',
  hostDistribution: 'Host-Verteilung',
  editSelfAccount: 'Eigenes Konto bearbeiten',
  securitySettings: 'Sicherheitseinstellungen',
  aboutQuarx: 'Über QUARX',
  HrTechnique: 'HRT',
  employeesList: 'Mitarbeiterliste',
  employeeSpecifications: 'Mitarbeiterspezifikationen',
  employees: 'Mitarbeiter',
  employeesDescription: 'Mitarbeiteraufzeichnungen, Spezifikationen',
  specification: 'Spezifikation',
  dateOfBirth: 'Geburtsdatum',
  postcode: 'Postleitzahl',
  userId: 'Benutzer-ID',
  companies: 'Unternehmen',
  housingAssistant: 'Wohnassistent',
  recruiter: 'E-Recruiter',
  documents: 'Dokumente',
  integrations: 'Integrationen',
  statistics: 'Statistiken',
  price: 'Preis',
  belongingProductsList: 'Produktliste',
  productCategories: 'Produktkategorien',
  productSpecifications: 'Produktspezifikationen',
  products: 'Produkte',
  productsDescription: 'Produktbeschreibung',
  shelves: 'Regale',
  loans: 'Darlehen',
  clients: 'Kunden',
  descriptionQuarx: 'QUARX (Qualified Unified Authorization and Resource eXchange)',
  descriptionQuarx1:
    'Es ist ein Autorisierungssystem für Systeme, die von Web-Alchemy bereitgestellt werden.',
  descriptionQuarx2:
    'Es ist eine unabhängige Lösung, die den Zugriff auf unsere Cloud-Dienste ermöglicht und grundlegende Sicherheitseinstellungen bietet.',
  descriptionQuarx3:
    'Das Tool ermöglicht den Zugriff auf Anwendungen basierend auf erteilten Lizenzen, die zusammen mit einem dedizierten Server vom Anbieter erworben werden können. Abhängig von ihrem Satz kann der Benutzer die verfügbaren Dienste nutzen.',
  descriptionQuarx4:
    'QUARX bietet auch statistische Module* und Datenanalyse aus integrierten Systemen.',
  descriptionQuarx5:
    '* Die Entwicklung der datenanalysierten Module wird mit Version 1.0Beta der ersten Systemtrilogie geliefert: QUARX, Lombandit und HRTechnique.',
  authDescriptionQuarx:
    'Die Autorisierung durch das QUARX-System schränkt den Zugriff auf unerwünschte Geräte effektiv ein, indem es eine Aufzeichnung führt und die Konfiguration von Parametern wie Zugriffsbeschränkungen und Netzwerk- und Gerätesperren ermöglicht. Das System ermöglicht auch die Durchsetzung der Autorisierung neuer Geräte, die Verkürzung der aktiven Sitzungszeiten und die Sperrung der Sitzungsaktualisierung. Dadurch bietet QUARX ein hohes Maß an Sicherheit und Kontrolle in einer verteilten Umgebung und schützt Ressourcen vor unbefugtem Zugriff.',
  authDescriptionQuarx1: '',
  authDescriptionQuarx2:
    'Mit dem QUARX-System ist es möglich, mehrere Anwendungen gleichzeitig mit einem einzigen, zentralen QUARX-Konto zu verwalten. Dies ermöglicht die Verwaltung mehrerer Unternehmen an einem Ort und erleichtert die Kontrolle und Administration verschiedener Prozesse erheblich.',
  authDescriptionQuarx3: '',
  authDescriptionQuarx4: '',
  authDescriptionQuarx5: '',

  licencesDescriptionQuarx:
    'Lizenzen werden mit dem Kauf der Software oder als Ergänzung zu bereits vorhandenen Produkten erworben. Sie werden zusammen mit einem dedizierten Server gewährt, der zusätzlich gesichert ist, um direkten Zugriff nur für den Kunden über VPN zu ermöglichen.',
  licencesDescriptionQuarx1: '',
  licencesDescriptionQuarx2: '',
  licencesDescriptionQuarx3: '',
  licencesDescriptionQuarx4: '',
  licencesDescriptionQuarx5: '',

  hostDescriptionQuarx:
    'Wir arbeiten mit Cloud-Servern eines vertrauenswürdigen Hosting-Dienstleisters. Wir sind flexibel und passen uns den Bedürfnissen des Kunden an, indem wir auch Dienste anbieten, die auf physischen Servern beim Kunden gehostet werden.',
  hostDescriptionQuarx1: '',
  hostDescriptionQuarx2: '',
  hostDescriptionQuarx3: '',
  hostDescriptionQuarx4: '',
  hostDescriptionQuarx5: '',

  usersDescriptionQuarx:
    'Der Administrator, der der Lizenzinhaber ist, erhält zusätzliche Berechtigungen und Zugang zur Benutzerverwaltung. Abhängig von der Lizenzgröße kann er eine bestimmte Anzahl von Konten an seine Mitarbeiter vergeben.',
  usersDescriptionQuarx1: '',
  usersDescriptionQuarx2:
    'Im "Kontoverwaltung"-Panel kann der Administrator verschiedene Inspektionen und Sicherheitskonfigurationen für einzelne zugehörige Konten durchführen. Das Tool ermöglicht es dem Manager, neue Geräteautorisierungen per E-Mail zu erzwingen, Sitzungszeiten zu verkürzen, die Sitzungsaktualisierung zu deaktivieren und die Selbsteinstellung von Einstellungen für untergeordnete Konten zu sperren.',
  usersDescriptionQuarx3:
    'Dieses Panel ermöglicht auch die Zuweisung von Lizenzen zu anderen Konten und die Bearbeitung persönlicher Daten der Benutzer.',
  usersDescriptionQuarx4: '',
  usersDescriptionQuarx5: '',

  quarxEarly:
    'QUARX befindet sich in der frühen Entwicklungsphase. Es erfüllt die grundlegenden Funktionen, die in der Dokumentation beschrieben sind. Mit einem Sternchen * markierte Funktionen sind für die endgültigen Versionen der Anwendung nach der vollständigen Implementierung der HRTechnique- und Lombandit-Systeme geplant.',

  docs: 'Dokumentation',

  securityDescriptionQuarx: '',
  securityDescriptionQuarx1:
    'Durchsetzung der neuen Geräteautorisierung: Der Administrator kann durchsetzen, dass jedes neue Gerät, das versucht, auf das System zuzugreifen, einen Autorisierungsprozess per E-Mail durchläuft. Dies stellt sicher, dass nur verifizierte Geräte Zugriff auf Ressourcen haben.',
  securityDescriptionQuarx2:
    'Verkürzung der Sitzungszeit: Der Administrator kann die maximale Dauer einer Benutzersitzung festlegen. Nach Ablauf dieser Zeit wird der Benutzer automatisch abgemeldet, was die Sicherheit erhöht, indem das Risiko des Zugriffs auf das Konto durch unbefugte Personen verringert wird.',
  securityDescriptionQuarx3:
    'Sitzungsaktualisierungssperre: Diese Funktion ermöglicht es dem Administrator, die automatische Sitzungsaktualisierung zu blockieren, wodurch Benutzer nach Ablauf der Sitzung gezwungen werden, sich erneut anzumelden, was eine zusätzliche Zugangskontrolle bietet.',
  securityDescriptionQuarx4:
    'Selbsteinstellungssperre: Der Administrator kann die Möglichkeit blockieren, dass Benutzer ihre Einstellungen selbst bearbeiten. Nur der Administrator kann Änderungen an Konfigurationen vornehmen, was unbefugte Änderungen verhindert und die Gesamtsicherheit des Systems erhöht.',
  securityDescriptionQuarx5: '',

  aboutHrt: 'HRTechnique',
  aboutLombandit: 'Lombandit',
  lombanditDocs: 'Lombandit-Dokumentation',
  lombanditDocsDescription: 'Grundlegendes Wissen über das System',
  hrtDocs: 'HRTechnique-Dokumentation',
  hrtDocsDescription: 'Grundlegendes Wissen über das System',
  quarxDocs: 'QUARX-Dokumentation',
  quarxDocsDescription: 'Grundlegendes Wissen über das System',
  Docs: 'Dokumente',
  QUARX: 'QUARX',
  Lombandit: 'Lombandit',
  HRTechniqe: 'HRTeqchnique',
  suppressSelfSecurityChanges: 'Unterdrücken von eigenen Sicherheitsänderungen',
  suppressSelfSecurityChangesDescription:
    'Beschreibung der Unterdrückung von eigenen Sicherheitsänderungen',
  securityChart: 'Geräte',
  monthlyVisits: 'Top 5 monatliche Besuche',
  monthlyActivities: 'Top 5 monatliche Aktivitäten',
};
