export const en = {
  ownedLicences: 'List of authorized licenses',
  ownedLicencesDescription:
    'Access to other system applications can be obtained from the software provider',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Name',
  changePassword: 'Change password',
  editPersonalDetails: 'Edit your details',
  oldPassword: 'Old password',
  unlockAccount: 'Unlock account',
  newPassword: 'New password',
  confirmNewPassword: 'Confirm new password',
  reNewPassword: 'Confirm new password',
  accountBlocked: 'Account has been blocked',
  firstName: 'First Name',
  lastName: 'Last Name',
  language: 'Language',
  blockAccount: 'Block Account',
  personalId: 'Personal ID',
  email: 'Email',
  personalPhone: 'Personal Phone',
  city: 'City',
  postCode: 'Postal Code',
  description: 'Description',
  address: 'Address',
  noNotifications: 'No Notifications',
  notifications: 'Notifications',
  companyNip: 'Tax Identification Number (NIP)',
  companyName: 'Company Name',
  dashboard: 'Dashboard',
  submit: 'Submit',
  more: 'More',
  companyAddress: 'Company Address',
  companyPhone: 'Company Phone',
  'Welcome to': 'Welcome to',
  'Empower your company with the best solutions': 'Empower your company with the best solutions',
  'Distribution, Access, and Integration System': 'Distribution, Access, and Integration System',
  'System for Employment & Recruitment Agencies': 'System for Employment & Recruitment Agencies',
  'Pawn shop system & micro warehouse distribution':
    'Pawn shop system & micro warehouse distribution',
  'QUARX Manager': 'QUARX Manager',
  'Secure Authorization System for Your Solutions':
    'Secure Authorization System for Your Solutions',
  usersSecurity: 'User Security',
  services: 'Services',
  youCanAuthorizeFromHere: 'You can authorize from here',
  emailTaken: 'Email Taken',
  website: 'Website',
  search: 'Search',
  notifyUser: 'Notify User',
  sendNotification: 'Send Notification',
  send: 'Send',
  receivers: 'Receivers',
  devicesOnline: 'Devices Online',
  noSelectedUsers: 'No Selected Users',
  title: 'Title',
  code: 'Code',
  'title-code': 'Title (Code)',
  pleaseChooseReceiver: 'Please choose receivers',
  close: 'Close',
  saveChanges: 'Save Changes',
  id: 'ID Number',
  usersSecuritySettingsLevel: 'Security Settings Level',
  verified: 'Verified',
  actions: 'Actions',
  successfullySent: 'Sent Successfully',
  successfullySentDescription: 'Notification has been sent successfully',
  selected: 'Selected',
  devices: 'Devices',
  dashboardDescription: 'Global preview and statistics',
  networks: 'Networks',
  blockIpAddress: 'Block IP Address',
  blockDevice: 'Block Device',
  serverDown: 'Server Down',
  'Network error': 'Network Error',
  unlockIpAddress: 'Unlock IP Address',
  saveNewUser: 'Save New User',
  unlockDevice: 'Unlock Device',
  host: 'Host',
  licenceUserQty: 'Maximal users quantity',
  software: 'Software',
  licenceStart: 'Licence start',
  licenceEnd: 'Licence end',
  authorize: 'Authorize',
  resetPassword: 'Reset Password',
  editYourAccount: 'Edit Your Account',
  newVerificationEmailHasBeenSent: 'New verification email has been sent',
  editYourAccountDescription: 'Personal Data, Password Change, License Information',
  info: 'Information',
  account: 'Account',
  available: 'Available',
  permitted: 'Permitted',
  belongingUsersList: 'Users',
  create: 'Create New',
  signedDevices: 'Assigned Devices',
  signedDevicesDescription: 'List of devices user logged in from',
  newDeviceEmailVerification: 'New Device Email Verification',
  newDeviceEmailVerificationDescription:
    'Activating this function will require email confirmation for every new device user logs in from',
  turnedOn: 'On',
  turnedOff: 'Off',
  removeSelected: 'Remove Selected',
  verifyDevice: 'Verify Device',
  verifyDeviceAdmin: 'Mark as Verified',
  profile: 'Profile',
  licences: 'Licences',
  editAccount: 'Settings',
  sessionExpiry: 'Session Expiry Time (min)',
  validTo: 'Session Valid Until:',
  refreshIn: 'Refresh In:',
  refreshLocked: 'Locked',
  sessionExpiryDescription: 'You can shorten or extend the default session time',
  suppressTokenRefresh: 'Suppress Token Refresh',
  suppressTokenRefreshDescription:
    'Activating this function will prevent your session from refreshing after the required time, causing the session to expire after its duration',
  users: 'Users',
  emailHasBeenChanged: 'Email has been changed',
  usersManagement: 'User Management',
  signOut: 'Sign Out',
  youAreLoggedIn: 'You are logged in. Log out',
  usersManagementDescription: 'Edit personal data, Access configuration',
  manageUsers: 'Manage Users',
  tools: 'Tools',
  security: 'Security',
  "The session will refresh upon any activity if the user's online time exceeds":
    "The session will automatically refresh upon any activity if the user's online time exceeds",
  minutes: 'minutes',
  'and do not exceeds': 'and does not exceed',
  ip: 'IP',
  userAgent: 'User Agent',
  deviceStatus: 'Device Status',
  verificationLinkHasBeenSentToYourNewAddress:
    'Verification link has been sent to your new email address',
  off: 'Off',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Please check your new email for the link or retry after 15 minutes',
  incorrectPassword: 'Incorrect Password',
  online: 'Online',
  blockedDevice: 'Blocked Device',
  emptyRequiredFields: 'Required fields are empty',
  password: 'Password',
  newEmail: 'New Email',
  changeEmail: 'Change Email',

  // Errors
  cannotBanOwnerIpAddress: "Cannot ban owner's IP address",
  youCannotBlockOngoingDevice: 'You cannot block ongoing device',
  thisDeviceHasBeenBlocked: 'This device has been blocked',
  youMustFillAnEmail: 'You must fill in an email',
  youMustFillAPassword: 'You must fill in a password',
  blockedIp: 'Blocked IP',
  ipHasBeenBlocked: 'Your IP has been blocked',
  'Request failed with status code 400': 'Bad request',
  'Request failed with status code 303': 'Verification',
  userDoesNotBelongToTheAccount: 'User does not belong to the account',
  deviceDoesNotBelongToTheAccount: 'Device does not belong to the account',
  dataInvalidAuthorizationKey: 'Error reading authorization data',
  somethingGoneWrong: 'Something went wrong',
  noAuthorizationKeyProvided: 'No authorization data provided',
  userWithThisEmailDoesNotExist: 'User with this email does not exist',
  youNeedToVerifyEmail:
    'You need to verify your email. Check your inbox or try again in 15 minutes',
  incorrectLoginData: 'Incorrect login data',
  sessionExpired: 'Session expired',
  invalidAuthorizationKey: 'Authorization process rejected',
  yourResetPasswordHasExpired: 'Your password reset session has expired. Please try again',
  incorrectOldPassword: 'Incorrect old password',
  youMustProvideValidPasswordConfirmation: 'You must provide a valid password confirmation',
  ' ': ' ',
  polish: 'Polish',
  english: 'English',
  german: 'German',
  dutch: 'Dutch',
  Serwisy: 'Services',
  youHaveAlreadyVerifiedYourAccount: 'You have already verified your account',
  userDoesNotExist: 'User does not exist',
  superAdmin: 'Super Administrator',
  admin: 'Administrator',
  user: 'User',
  'Active session time (min)': 'Active session time (min)',
  login: 'Sign in',
  noLicenceOwned: 'Unavailability of the required licenses',
  welcome: 'Welcome',
  'Devices Quantity': 'Devices Quantity',
  'Blocked Devices': 'Blocked Devices',
  'Blocked IPs': 'Blocked IPs',
  userIsNotVerified: 'User is not verified',
  deviceVerified: 'Device has been verified',
  pleaseCheckYourEmailOrRetryAfter15minutes: 'Please check your email or retry after 15 minutes',
  deviceAlreadyBlocked: 'Device is already blocked',
  ipAlreadyBlocked: 'IP address is already blocked',
  updatedUserCouldNotBeFound: 'Updated user could not be found',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Password reset has already been sent to your email. Please check your email or retry after 15 minutes.',
  verificationFailed: 'Verification failed',
  // Messages
  rowHasBeenUpdated: 'Row has been updated',
  setNewPassword: 'Set new password',
  emailsAreEqual: 'Emails are equal',
  lastSignIn: 'Last sign-in',
  verifiedDevice: 'Verified Device',
  yourPasswordHasBeenSuccessfullyChanged: 'Your password has been successfully changed',
  visitMailBoxAndConfirmPasswordReset: 'Visit your mailbox and confirm password reset',
  passwordChanged: 'Password changed',
  passwordHasBeenChanged: 'Password has been changed',
  passwordHasBeenChangedDescription: 'Your data has been updated',
  confirmationEmailHasBeenSent: 'Confirmation email has been sent',
  userCreated: 'User has been created',

  //ciagi
  _Auth: 'Auth',
  _orizationManager: `Manager`,

  //5-23-2024
  authorization: 'Authorization',
  hostDistribution: 'Host Distribution',
  editSelfAccount: 'Edit Self Account',
  securitySettings: 'Security Settings',
  aboutQuarx: 'About QUARX',
  HrTechnique: 'HRT',
  employeesList: 'Employees List',
  employeeSpecifications: 'Employee Specifications',
  employees: 'Employees',
  employeesDescription: 'Employee Records, Specifications',
  specification: 'Specification',
  dateOfBirth: 'Date of Birth',
  postcode: 'Postcode',
  userId: 'User ID',
  companies: 'Companies',
  housingAssistant: 'Housing Assistant',
  recruiter: 'E-Recruiter',
  documents: 'Documents',
  integrations: 'Integrations',
  statistics: 'Statistics',
  price: 'Price',
  belongingProductsList: 'Belonging Products List',
  productCategories: 'Product Categories',
  productSpecifications: 'Product Specifications',
  products: 'Products',
  productsDescription: 'Products Description',
  shelves: 'Shelves',
  loans: 'Loans',
  clients: 'Clients',
  descriptionQuarx: 'QUARX (Qualified Unified Authorization and Resource eXchange)',
  descriptionQuarx1: 'It is an authorization system for systems provided by Web-Alchemy.',
  descriptionQuarx2:
    'It is an independent solution that enables access to our cloud services and provides basic security settings control.',
  descriptionQuarx3:
    'The tool allows access to applications based on granted licenses, which can be purchased from the provider along with a dedicated server. Depending on their set, the user can use the available services.',
  descriptionQuarx4:
    'QUARX also provides statistical modules* and data analysis from integrated systems.',
  descriptionQuarx5:
    '* The development of data analysis-based modules will be delivered with version 1.0Beta of the first systems trilogy: QUARX, Lombandit, and HRTechnique.',

  authDescriptionQuarx:
    'Authorization through the QUARX system effectively restricts access to unwanted devices by keeping a record and allowing configuration of parameters such as access restrictions and network and device locks. The system also allows for the enforcement of new device authorization, shortening of active session times, and session refresh blocking. As a result, QUARX provides a high level of security and control in a distributed environment, protecting resources from unauthorized access.',
  authDescriptionQuarx1: '',
  authDescriptionQuarx2:
    'With the QUARX system, it is possible to simultaneously handle multiple applications using a single, central QUARX account. This allows managing multiple businesses in one place, greatly facilitating control and administration of various processes.',
  authDescriptionQuarx3: '',
  authDescriptionQuarx4: '',
  authDescriptionQuarx5: '',

  licencesDescriptionQuarx:
    'Licenses are obtained with the purchase of software or as an add-on to already owned products. They are granted along with a dedicated server, which is additionally secured to provide direct access only for the client using VPN.',
  licencesDescriptionQuarx1: '',
  licencesDescriptionQuarx2: '',
  licencesDescriptionQuarx3: '',
  licencesDescriptionQuarx4: '',
  licencesDescriptionQuarx5: '',

  hostDescriptionQuarx:
    'We work on cloud servers with a trusted hosting service provider. We are flexible, so we adapt to the clients needs, also offering services hosted on physical servers at the client’s location.',
  hostDescriptionQuarx1: '',
  hostDescriptionQuarx2: '',
  hostDescriptionQuarx3: '',
  hostDescriptionQuarx4: '',
  hostDescriptionQuarx5: '',

  usersDescriptionQuarx:
    'The administrator, who is the license owner, gains additional privileges and access to user management. Depending on the license size, they can assign a specified number of accounts to their employees.',
  usersDescriptionQuarx1: '',
  usersDescriptionQuarx2:
    'In the "Account Management" panel, the administrator can perform various inspections and security configurations for individual related accounts. The tool allows the manager to enforce new device authorization via email, shorten session times, disable session refresh, and block self-editing of settings for subordinate accounts.',
  usersDescriptionQuarx3:
    'This panel also enables assigning owned licenses to other accounts and editing users’ personal data.',
  usersDescriptionQuarx4: '',
  usersDescriptionQuarx5: '',
  quarxEarly:
    " QUARX is in the early stages of development. It fulfills the basic functions outlined in the documentation. Functionality marked with an asterisk * is planned for the final versions of the application, after the full implementation of the HRTechnique and Lombandit systems.'\n",
  docs: 'Documentation',

  securityDescriptionQuarx: '',
  securityDescriptionQuarx1:
    'Enforcing new device authorization: The administrator can enforce that every new device attempting to access the system undergoes an authorization process via email. This ensures that only verified devices have access to resources.',
  securityDescriptionQuarx2:
    'Session time reduction: The administrator can set the maximum duration of a user session. After this time, the user will be automatically logged out, increasing security by reducing the risk of account access by unauthorized persons.',
  securityDescriptionQuarx3:
    'Session refresh blocking: This feature allows the administrator to block automatic session refresh, forcing users to re-login after the session ends, providing an additional level of access control.',
  securityDescriptionQuarx4:
    'Self-edit settings block: The administrator can block the ability of users to edit settings on their own. Only the administrator can make changes to configurations, preventing unauthorized modifications and increasing the overall security of the system.',
  securityDescriptionQuarx5: '',

  aboutHrt: 'HRTechnique',
  aboutLombandit: 'Lombandit',
  lombanditDocs: 'Lombandit Documentation',
  lombanditDocsDescription: 'Basic knowledge about the system',
  hrtDocs: 'HRTechnique Documentation',
  hrtDocsDescription: 'Basic knowledge about the system',
  quarxDocs: 'QUARX Documentation',
  quarxDocsDescription: 'Basic knowledge about the system',
  Docs: 'Docs',
  QUARX: 'QUARX',
  Lombandit: 'Lombandit',
  HRTechniqe: 'HRTeqchnique',
  suppressSelfSecurityChanges: 'Onderdrukken van eigen beveiligingswijzigingen',
  suppressSelfSecurityChangesDescription:
    'Beschrijving van onderdrukken van eigen beveiligingswijzigingen',
  securityChart: 'Devices',
  monthlyVisits: 'Top 5 monthly visits',
  monthlyActivities: 'Top 5 monthly activities',
};
