export const nl = {
  ownedLicences: 'Lijst van geautoriseerde licenties',
  ownedLicencesDescription:
    'Toegang tot andere systeemtoepassingen kunt u verkrijgen van de softwareleverancier',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Naam',
  changePassword: 'Wijzig wachtwoord',
  editPersonalDetails: 'Bewerk uw persoonlijke gegevens',
  oldPassword: 'Oud wachtwoord',
  unlockAccount: 'Ontgrendel account',
  newPassword: 'Nieuw wachtwoord',
  confirmNewPassword: 'Bevestig nieuw wachtwoord',
  reNewPassword: 'Bevestig nieuw wachtwoord',
  accountBlocked: 'Account is geblokkeerd',
  firstName: 'Voornaam',
  lastName: 'Achternaam',
  language: 'Taal',
  blockAccount: 'Blokkeren account',
  personalId: 'Persoonlijk identificatienummer',
  email: 'E-mail',
  personalPhone: 'Persoonlijk telefoonnummer',
  city: 'Stad',
  postCode: 'Postcode',
  description: 'Beschrijving',
  address: 'Adres',
  noNotifications: 'Geen meldingen',
  'Welcome to': 'Welkom bij',
  'Empower your company with the best solutions': 'Versterk uw bedrijf met de beste oplossingen',
  notifications: 'Meldingen',
  companyNip: 'Belastingnummer',
  'Distribution, Access, and Integration System': 'Distributie-, toegangs- en integratiesysteem',
  'System for Employment & Recruitment Agencies': 'Systeem voor Arbeids- en Wervingsbureaus',
  'Pawn shop system & micro warehouse distribution': 'Pandjessysteem & micro-opslag distributie',
  'QUARX Manager': 'QUARX Manager',
  more: 'Meer',
  'Secure Authorization System for Your Solutions':
    'Beveiligd autorisatiesysteem voor uw oplossingen',
  submit: 'Verzenden',
  companyName: 'Bedrijfsnaam',
  dashboard: 'Dashboard',
  companyAddress: 'Bedrijfsadres',
  'Page Size:': 'Paginagrootte:',
  pageSizeSelectorLabel: 'Paginagrootte:',
  dashboardDescription: 'Overzicht van wijzigingen, algemene statistieken',
  host: 'Host',
  authorize: 'Autoriseren',
  licenceUserQty: 'Maximaal aantal gelicentieerde gebruikers',
  newVerificationEmailHasBeenSent: 'Nieuwe verificatie-e-mail is verzonden',
  software: 'Software',
  licenceStart: 'Start licentieperiode',
  licenceEnd: 'Einde licentieperiode',
  companyPhone: 'Bedrijfstelefoon',
  usersSecurity: 'Gebruikersbeveiliging',
  services: 'Diensten',
  youCanAuthorizeFromHere: 'U kunt hier autoriseren',
  emailTaken: 'E-mail bezet',
  website: 'Website',
  search: 'Zoeken',
  notifyUser: 'Gebruiker op de hoogte stellen',
  sendNotification: 'Notificatie verzenden',
  send: 'Verzenden',
  receivers: 'Ontvangers',
  devicesOnline: 'Apparaten online',
  noSelectedUsers: 'Geen geselecteerde gebruikers',
  title: 'Titel',
  code: 'Code',
  'title-code': 'Titel (Code)',
  pleaseChooseReceiver: 'Selecteer gebruikers om ontvangers te kiezen',
  close: 'Sluiten',
  saveChanges: 'Wijzigingen opslaan',
  id: 'ID-nummer',
  usersSecuritySettingsLevel: 'Beveiligingsniveau gebruikers',
  verified: 'Geverifieerd',
  actions: 'Acties',
  successfullySent: 'Succesvol verzonden',
  successfullySentDescription: 'Notificatie is succesvol verzonden',
  selected: 'Geselecteerd',
  devices: 'Apparaten',
  networks: 'Netwerken',
  blockIpAddress: 'IP-adres blokkeren',
  blockDevice: 'Apparaat blokkeren',
  serverDown: 'Server niet beschikbaar',
  'Network error': 'Netwerkfout',
  unlockIpAddress: 'IP-adres deblokkeren',
  saveNewUser: 'Nieuwe gebruiker opslaan',
  unlockDevice: 'Apparaat deblokkeren',
  resetPassword: 'Wachtwoord resetten',
  editYourAccount: 'Accountinstellingen bewerken',
  editYourAccountDescription: 'Persoonlijke gegevens, wachtwoord wijzigen, licentiegegevens',
  info: 'Informatie',
  account: 'Account',
  available: 'Beschikbaar',
  permitted: 'Toegestaan',
  polish: 'Pools',
  english: 'Engels',
  german: 'Duits',
  dutch: 'Nederlands',
  belongingUsersList: 'Lijst met bijbehorende gebruikers',
  noLicenceOwned: 'Geen licenties in bezit',
  create: 'Nieuw aanmaken',
  signedDevices: 'Ondertekende apparaten',
  signedDevicesDescription: 'Lijst van apparaten waarop de gebruiker is ingelogd',
  newDeviceEmailVerification: 'E-mailverificatie voor nieuwe apparaten',
  newDeviceEmailVerificationDescription:
    'Door deze functie te activeren, vereist elk nieuw apparaat waarop de gebruiker inlogt een bevestiging via e-mail',
  turnedOn: 'Ingeschakeld',
  turnedOff: 'Uitgeschakeld',
  removeSelected: 'Geselecteerde verwijderen',
  verifyDevice: 'Apparaat verifiëren',
  verifyDeviceAdmin: 'Instellen als geverifieerd',
  profile: 'Profiel',
  authDescriptionQuarx:
    'Autorisatie via het QUARX-systeem beperkt effectief de toegang tot ongewenste apparaten door een registratie bij te houden en de configuratie van parameters zoals toegangsbeperkingen en netwerk- en apparaatsloten mogelijk te maken. Het systeem maakt ook de handhaving van nieuwe apparaatautorisatie, verkorting van actieve sessietijden en blokkering van sessieverversing mogelijk. Als resultaat biedt QUARX een hoog niveau van beveiliging en controle in een gedistribueerde omgeving en beschermt het middelen tegen ongeautoriseerde toegang.',
  authDescriptionQuarx1: '',
  authDescriptionQuarx2:
    'Met het QUARX-systeem is het mogelijk om meerdere toepassingen gelijktijdig te beheren met één centraal QUARX-account. Dit maakt het beheer van meerdere bedrijven op één plaats mogelijk en vergemakkelijkt de controle en administratie van verschillende processen aanzienlijk.',
  authDescriptionQuarx3: '',
  authDescriptionQuarx4: '',
  authDescriptionQuarx5: '',

  licencesDescriptionQuarx:
    'Licenties worden verkregen bij de aankoop van software of als aanvulling op reeds bestaande producten. Ze worden verleend samen met een dedicated server, die extra beveiligd is om directe toegang alleen voor de klant via VPN mogelijk te maken.',
  licencesDescriptionQuarx1: '',
  licencesDescriptionQuarx2: '',
  licencesDescriptionQuarx3: '',
  licencesDescriptionQuarx4: '',
  licencesDescriptionQuarx5: '',

  hostDescriptionQuarx:
    'We werken met cloudservers van een vertrouwde hostingprovider. We zijn flexibel en passen ons aan de behoeften van de klant aan door ook diensten aan te bieden die op fysieke servers bij de klant worden gehost.',
  hostDescriptionQuarx1: '',
  hostDescriptionQuarx2: '',
  hostDescriptionQuarx3: '',
  hostDescriptionQuarx4: '',
  hostDescriptionQuarx5: '',

  usersDescriptionQuarx:
    'De beheerder, die de licentiehouder is, krijgt extra rechten en toegang tot gebruikersbeheer. Afhankelijk van de licentieomvang kan hij een bepaald aantal accounts toewijzen aan zijn medewerkers.',
  usersDescriptionQuarx1: '',
  usersDescriptionQuarx2:
    'In het "Accountbeheer"-paneel kan de beheerder verschillende inspecties en beveiligingsconfiguraties uitvoeren voor individuele gerelateerde accounts. Het hulpmiddel stelt de manager in staat om nieuwe apparaatautorisaties via e-mail af te dwingen, sessietijden te verkorten, sessieverversing uit te schakelen en het zelfstandig aanpassen van instellingen voor ondergeschikte accounts te blokkeren.',
  usersDescriptionQuarx3:
    'Dit paneel maakt ook de toewijzing van licenties aan andere accounts en het bewerken van persoonlijke gegevens van gebruikers mogelijk.',
  usersDescriptionQuarx4: '',
  usersDescriptionQuarx5: '',

  quarxEarly:
    'QUARX bevindt zich in een vroeg ontwikkelingsstadium. Het vervult de basisfuncties die in de documentatie worden beschreven. Functionaliteit gemarkeerd met een sterretje * is gepland voor de definitieve versies van de toepassing, na de volledige implementatie van de HRTechnique- en Lombandit-systemen.',

  docs: 'Documentatie',

  securityDescriptionQuarx: '',
  securityDescriptionQuarx1:
    'Handhaving van nieuwe apparaatautorisatie: De beheerder kan afdwingen dat elk nieuw apparaat dat probeert toegang te krijgen tot het systeem een autorisatieproces via e-mail doorloopt. Dit zorgt ervoor dat alleen geverifieerde apparaten toegang hebben tot middelen.',
  securityDescriptionQuarx2:
    'Verkorting van sessietijd: De beheerder kan de maximale duur van een gebruikerssessie instellen. Na deze tijd wordt de gebruiker automatisch uitgelogd, waardoor de beveiliging wordt verhoogd door het risico op toegang tot het account door onbevoegde personen te verminderen.',
  securityDescriptionQuarx3:
    'Blokkering van sessieverversing: Met deze functie kan de beheerder de automatische sessieverversing blokkeren, waardoor gebruikers na afloop van de sessie opnieuw moeten inloggen, wat een extra niveau van toegangscontrole biedt.',
  securityDescriptionQuarx4:
    'Blokkering van het zelfstandig aanpassen van instellingen: De beheerder kan de mogelijkheid blokkeren dat gebruikers hun instellingen zelf aanpassen. Alleen de beheerder kan wijzigingen aanbrengen in configuraties, wat ongeautoriseerde wijzigingen voorkomt en de algehele beveiliging van het systeem verhoogt.',
  securityDescriptionQuarx5: '',

  aboutHrt: 'HRTechnique',
  aboutLombandit: 'Lombandit',
  lombanditDocs: 'Lombandit-documentatie',
  lombanditDocsDescription: 'Basiskennis over het systeem',
  hrtDocs: 'HRTechnique-documentatie',
  hrtDocsDescription: 'Basiskennis over het systeem',
  quarxDocs: 'QUARX-documentatie',
  quarxDocsDescription: 'Basiskennis over het systeem',
  authorization: 'Autorisatie',
  hostDistribution: 'Hostdistributie',
  editSelfAccount: 'Eigen account bewerken',
  securitySettings: 'Beveiligingsinstellingen',
  aboutQuarx: 'Over QUARX',
  HrTechnique: 'HRT',
  employeesList: 'Werknemerslijst',
  employeeSpecifications: 'Werknemersspecificaties',
  employees: 'Werknemers',
  employeesDescription: 'Werknemersdossiers, specificaties',
  specification: 'Specificatie',
  dateOfBirth: 'Geboortedatum',
  postcode: 'Postcode',
  userId: 'Gebruikers-ID',
  companies: 'Bedrijven',
  housingAssistant: 'Huisvestingsassistent',
  recruiter: 'E-Recruiter',
  documents: 'Documenten',
  integrations: 'Integraties',
  statistics: 'Statistieken',
  price: 'Prijs',
  belongingProductsList: 'Lijst van bijbehorende producten',
  productCategories: 'Productcategorieën',
  productSpecifications: 'Productspecificaties',
  products: 'Producten',
  productsDescription: 'Productbeschrijving',
  shelves: 'Planken',
  loans: 'Leningen',
  clients: 'Klanten',
  descriptionQuarx: 'QUARX (Qualified Unified Authorization and Resource eXchange)',
  descriptionQuarx1:
    'Het is een autorisatiesysteem voor systemen die door Web-Alchemy worden geleverd.',
  descriptionQuarx2:
    'Het is een onafhankelijke oplossing die toegang tot onze cloudservices mogelijk maakt en basiscontrole over beveiligingsinstellingen biedt.',
  descriptionQuarx3:
    'De tool biedt toegang tot applicaties op basis van verleende licenties, die samen met een dedicated server bij de provider kunnen worden gekocht. Afhankelijk van hun set kan de gebruiker de beschikbare diensten gebruiken.',
  descriptionQuarx4:
    'QUARX biedt ook statistische modules* en data-analyse van geïntegreerde systemen.',
  descriptionQuarx5:
    '* De ontwikkeling van op data-analyse gebaseerde modules wordt geleverd met versie 1.0Beta van de eerste systeemtrilogie: QUARX, Lombandit en HRTechnique.',
  licences: 'Licenties',
  editAccount: 'Account bewerken',
  sessionExpiry: 'Sessie verlooptijd (min)',
  validTo: 'Geldig tot:',
  refreshIn: 'Vernieuwen in:',
  refreshLocked: 'Vernieuwing geblokkeerd',
  sessionExpiryDescription: 'U kunt de standaard sessieduur verkorten of verlengen',
  suppressTokenRefresh: 'Vernieuwing van tokens onderdrukken',
  suppressTokenRefreshDescription:
    'Als deze functie is ingeschakeld, wordt uw sessie niet vernieuwd na de ingestelde tijd, wat resulteert in het verlopen van de sessie',
  users: 'Gebruikers',
  emailHasBeenChanged: 'E-mail is gewijzigd',
  usersManagement: 'Gebruikersbeheer',
  signOut: 'Afmelden',
  youAreLoggedIn: 'U bent ingelogd.',
  usersManagementDescription: 'Bewerken van persoonlijke gegevens, toegangsconfiguratie',
  manageUsers: 'Beheer gebruikers',
  tools: 'Tools',
  security: 'Veiligheid',
  "The session will refresh upon any activity if the user's online time exceeds":
    'De sessie wordt vernieuwd bij elke activiteit als de online tijd van de gebruiker de limiet overschrijdt',
  minutes: 'minuten',
  'and do not exceeds': 'en overschrijdt niet',
  ip: 'IP',
  userAgent: 'Apparaat',
  deviceStatus: 'Apparaatstatus',
  verificationLinkHasBeenSentToYourNewAddress:
    'Verificatielink is verzonden naar uw nieuwe e-mailadres',
  off: 'Uitgeschakeld',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Controleer uw nieuwe e-mail voor de link of probeer het na 15 minuten opnieuw',
  incorrectPassword: 'Onjuist wachtwoord',
  online: 'Online',
  blockedDevice: 'Geblokkeerd apparaat',
  emptyRequiredFields: 'Verplichte velden zijn leeg',
  password: 'Wachtwoord',
  newEmail: 'Nieuwe e-mail',
  changeEmail: 'Verander e-mailadres',

  // fouten
  cannotBanOwnerIpAddress: 'Kan het huidige IP-adres van de eigenaar niet blokkeren',
  youCannotBlockOngoingDevice: 'U kunt het huidige apparaat niet blokkeren',
  thisDeviceHasBeenBlocked: 'Dit apparaat is geblokkeerd',
  youMustFillAnEmail: 'U moet een e-mailadres invullen',
  youMustFillAPassword: 'U moet een wachtwoord invullen',
  blockedIp: 'Geblokkeerd IP-adres',
  ipHasBeenBlocked: 'Uw IP-adres is geblokkeerd',
  'Request failed with status code 400': 'Foutief verzoek met statuscode 400',
  'Request failed with status code 303': 'Verificatie',
  userDoesNotBelongToTheAccount: 'Gebruiker behoort niet tot uw account',
  deviceDoesNotBelongToTheAccount: 'Apparaat behoort niet tot het account',
  dataInvalidAuthorizationKey: 'Ongeldige autorisatiesleutel',
  somethingGoneWrong: 'Er is iets misgegaan',
  noAuthorizationKeyProvided: 'Geen autorisatiesleutel verstrekt',
  userWithThisEmailDoesNotExist: 'Gebruiker met dit e-mailadres bestaat niet',
  youNeedToVerifyEmail:
    'Verifieer e-mail. Controleer uw inbox of probeer het opnieuw over 15 minuten',
  incorrectLoginData: 'Onjuiste inloggegevens',
  sessionExpired: 'Sessie verlopen',
  invalidAuthorizationKey: 'Ongeldige autorisatiesleutel',
  yourResetPasswordHasExpired: 'Uw wachtwoordreset-sessie is verlopen. Probeer het opnieuw',
  incorrectOldPassword: 'Oud wachtwoord is onjuist',
  youMustProvideValidPasswordConfirmation:
    'U moet het wachtwoord correct herhalen om te bevestigen',
  ' ': ' ',
  Serwisy: 'Diensten',
  youHaveAlreadyVerifiedYourAccount: 'Je hebt je account al geverifieerd',
  userDoesNotExist: 'Gebruiker bestaat niet',
  superAdmin: 'Superbeheerder',
  admin: 'Beheerder',
  user: 'Gebruiker',
  'Czas aktywnej sesji (min)': 'Actieve sessietijd (min)',
  login: 'Inloggen',
  welcome: 'Welkom',
  'Devices Quantity': 'Aantal apparaten',
  'Blocked Devices': 'Geblokkeerde apparaten',
  'Blocked IPs': 'Geblokkeerde IP-adressen',
  userIsNotVerified: 'Gebruiker is niet geverifieerd',
  deviceVerified: 'Apparaat is geverifieerd',
  pleaseCheckYourEmailOrRetryAfter15minutes:
    'Controleer uw e-mail of probeer het opnieuw na 15 minuten',
  deviceAlreadyBlocked: 'Apparaat is al geblokkeerd',
  ipAlreadyBlocked: 'IP-adres is al geblokkeerd',
  updatedUserCouldNotBeFound: 'Gebruiker kon niet worden gevonden',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Reset wachtwoord is al naar uw e-mail verzonden. Controleer uw e-mail of probeer het opnieuw na 15 minuten.',
  verificationFailed: 'Verificatie mislukt',
  rowHasBeenUpdated: 'Rij is bijgewerkt',
  setNewPassword: 'Stel een nieuw wachtwoord in',
  emailsAreEqual: 'E-mails zijn gelijk',
  lastSignIn: 'Laatste aanmelding',
  verifiedDevice: 'Geverifieerd apparaat',
  yourPasswordHasBeenSuccessfullyChanged: 'Uw wachtwoord is succesvol gewijzigd',
  visitMailBoxAndConfirmPasswordReset: 'Ga naar uw postvak en bevestig het wachtwoordherstel',
  monthlyVisits: 'Top 5 maandelijkse bezoeken',
  monthlyActivities: 'Top 5 maandelijkse activiteiten',
  passwordChanged: 'Wachtwoord is gewijzigd',
  passwordHasBeenChanged: 'Wachtwoord is gewijzigd',
  passwordHasBeenChangedDescription: 'Uw gegevens zijn gewijzigd',
  confirmationEmailHasBeenSent: 'Bevestigingsmail is verzonden',
  _Auth: 'Authenticatie',
  _orizationManager: 'autorisatiemanager',
  userCreated: 'Gebruiker is toegevoegd',
  Docs: 'Documenten',
  QUARX: 'QUARX',
  Lombandit: 'Lombandit',
  HRTechniqe: 'HRTeqchnique',
  suppressSelfSecurityChanges: 'Onderdrukken van eigen beveiligingswijzigingen',
  suppressSelfSecurityChangesDescription:
    'Beschrijving van onderdrukken van eigen beveiligingswijzigingen',
  securityChart: 'Apparaten',
};
