export const pl = {
  ownedLicences: 'Lista autoryzowanych licencji',
  ownedLicencesDescription:
    'Dostęp do innych aplikacji systemu możesz uzyskać od dostawcy oprogramowania',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Nazwa',
  changePassword: 'Zmień hasło',
  editPersonalDetails: 'Edytuj swoje dane',
  oldPassword: 'Stare hasło',
  unlockAccount: 'Odblokuj konto',
  newPassword: 'Nowe hasło',
  confirmNewPassword: 'Potwierdź nowe hasło',
  reNewPassword: 'Potwierdź nowe hasło',
  accountBlocked: 'Konto zostało zablokowane',
  firstName: 'Imię',
  lastName: 'Nazwisko',
  language: 'Język',
  blockAccount: 'Zablokuj konto',
  personalId: 'Pesel',
  email: 'Email',
  personalPhone: 'Telefon prywatny',
  city: 'Miasto',
  postCode: 'Kod pocztowy',
  description: 'Opis',
  address: 'Adres',
  noNotifications: 'Brak powiadomień',
  'Welcome to': 'Witaj w',
  'Empower your company with the best solutions': 'Wzmocnij swoją firmę najlepszymi rozwiązaniami',
  notifications: 'Powiadomienia',
  companyNip: 'Nip',
  'Distribution, Access, and Integration System': 'System Dystrybucji, Dostępu i Integracji',
  'System for Employment & Recruitment Agencies': 'System dla Agencji Zatrudnienia i Rekruterów',
  'Pawn shop system & micro warehouse distribution': 'System dla lombardów i mikromagazynów',
  'QUARX Manager': 'QUARX Menadżer',
  more: 'Więcej',
  'Secure Authorization System for Your Solutions':
    'Bezpieczny system autoryzacyjny dla twoich rozwiązań',
  submit: 'Zatwierdź',
  companyName: 'Nazwa firmy',
  dashboard: 'Panel',
  companyAddress: 'Adres firmy',
  'Page Size:': 'Ilość na stronę',
  pageSizeSelectorLabel: 'Ilość na stronę',
  dashboardDescription: 'Podgląd zmian, statystyka ogólna',
  host: 'Host',
  authorize: 'Autoryzacja',
  licenceUserQty: 'Maksymalna liczba licencjonwanych użytkowników',
  newVerificationEmailHasBeenSent: 'Nowy email weryfikacyjny został wysłany',
  software: 'Oprogramowanie',
  licenceStart: 'Czas rozpoczęcia licencji',
  licenceEnd: 'Czas zakończenia licencji',
  companyPhone: 'Telefon służbowy',
  usersSecurity: 'Podgląd',
  services: 'Serwisy',
  youCanAuthorizeFromHere: 'Możesz się stąd autoryzować',
  emailTaken: 'Email zajęty',
  website: 'Adres www',
  search: 'Szukaj',
  notifyUser: 'Wyślij powiadomienie',
  sendNotification: 'Wyślij powiadomienie',
  send: 'Prześlij',
  receivers: 'Odbiorcy',
  devicesOnline: 'Urządzenia online',
  noSelectedUsers: 'Brak wybranych odbiorców',
  title: 'Tytuł',
  code: 'Kod',
  'title-code': 'Tytuł (Kod)',
  pleaseChooseReceiver: 'Zaznacz użytkowników aby wybrać odbiorców',
  close: 'Zamknij',
  saveChanges: 'Zapisz zmiany',
  id: 'Numer ID',
  usersSecuritySettingsLevel: 'Poziom bezpieczeństwa',
  verified: 'Zweryfikowany',
  actions: 'Zaawansowane',
  successfullySent: 'Wysłano',
  successfullySentDescription: 'Powiadomienie zostało przesłane z powodzeniem',
  selected: 'Wybrane',
  devices: 'Urządzenia',
  networks: 'Sieć',
  blockIpAddress: 'Zablokuj adres IP',
  blockDevice: 'Zablokuj urządzenie',
  serverDown: 'Serwer nie odpowiada',
  'Network error': 'Błąd połaczenia',
  unlockIpAddress: 'Odblokuj adres IP',
  saveNewUser: 'Zapisz',
  unlockDevice: 'Oblokuj urządzenie',
  resetPassword: 'Reset hasła',
  editYourAccount: 'Ustawienia konta',
  editYourAccountDescription: 'Dane osobowe, zmiana hasła, informacje o licencjach',
  info: 'Informacje',
  account: 'Konto',
  available: 'Dostępne',
  permitted: 'Przydzielone',
  polish: 'Polski',
  english: 'Angielski',
  german: 'Niemiecki',
  dutch: 'Niderlandzki',
  belongingUsersList: 'Użytkownicy',
  noLicenceOwned: 'Brak posiadanych licencji',
  create: 'Stwórz nowy',
  signedDevices: 'Przypisane urządzenia',
  signedDevicesDescription: 'Lista urządzeń na których loguje się użytkownik',
  newDeviceEmailVerification: 'Weryfikacja urządzeń przez Email',
  newDeviceEmailVerificationDescription:
    'Aktywyjąc tą funkcję każde nowe urządzenie, z którego loguje się użytkownik, będzie wymagało potwierdzenia przez pocztę email',
  turnedOn: 'Aktywowane',
  turnedOff: 'Dezaktywowane',
  removeSelected: 'Usuń zaznaczone',
  verifyDevice: 'Zweryfikuj urządzenie',
  verifyDeviceAdmin: 'Ustaw jako zweryfikowane',
  profile: 'Profil',
  licences: 'Licencje',
  editAccount: 'Ustawienia',
  sessionExpiry: 'Czas aktywnej sesji (min)',
  validTo: 'Sesja aktywna do:',
  refreshIn: 'Odświeżenie za:',
  refreshLocked: 'Wyłączono',
  sessionExpiryDescription: 'Moźesz skrócić lub przedłużyć domyślny czas sesji',
  suppressTokenRefresh: 'Wyłącz odnawianie sesji',
  suppressTokenRefreshDescription:
    'Ta funkcja uruchomiona spowoduje, że twoja sesja nie będzie się odnawiać po wymaganym czasie. Spowoduje to wygaśnięcie sesji po czasie jej trawnia',
  users: 'Użytkownicy',
  emailHasBeenChanged: 'Email został zmieniony',
  usersManagement: 'Zarządzanie użytkownikami',
  signOut: 'Wyloguj',
  youAreLoggedIn: 'Wyloguj sie.',
  usersManagementDescription: 'Edycja danych osobowych, Konfiguracja dostępu',
  manageUsers: 'Zarządzanie',
  tools: 'Narzędzia',
  security: 'Bezpieczeństwo',
  "The session will refresh upon any activity if the user's online time exceeds":
    'Sesja odnowi się automatycznie podczas aktywności jeśli czas zalogowania użytkownika przeczoczy',
  minutes: 'minut',
  'and do not exceeds': 'i nie przekroczy',
  ip: 'IP',
  userAgent: 'Urządzenie',
  deviceStatus: 'Status urządzenia',
  verificationLinkHasBeenSentToYourNewAddress: 'Link weryfikacyjny został wysłany na nowy email',
  off: 'Wygaszony',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Wykorzystaj link wysłany na nowy adres, lub odczekaj 15 minut i spróbuj znowu',
  incorrectPassword: 'Niepoprawne hasło',
  online: 'Aktywny',
  blockedDevice: 'Zablokowane urządzenie',
  emptyRequiredFields: 'Wymagane pola są puste',
  password: 'Hasło',
  newEmail: 'Nowy email',
  changeEmail: 'Zmień adres Email',

  //bledy
  cannotBanOwnerIpAddress: 'Nie można zbanować bieżącego adresu IP',
  youCannotBlockOngoingDevice: 'Nie można zbanować bieżącego urządzenia',
  thisDeviceHasBeenBlocked: 'Urządznie zostało zablokowane',
  youMustFillAnEmail: 'Wypełnij polę Email',
  youMustFillAPassword: 'Wypełnij pole hasło',
  blockedIp: 'Zablokowana sieć',
  ipHasBeenBlocked: 'Twoja sieć została zablokowana',
  'Request failed with status code 400': 'Błędne żądanie',
  'Request failed with status code 303': 'Weryfikacja',
  userDoesNotBelongToTheAccount: 'Użytkownik nie należy do twojego konta',
  deviceDoesNotBelongToTheAccount: 'Urządzenie nie należy do konta',
  dataInvalidAuthorizationKey: 'Błąd z odczytem danych autoryzacji',
  somethingGoneWrong: 'Coś poszło nie tak',
  noAuthorizationKeyProvided: 'Nie dostarczono danych autoryzacyjnych',
  userWithThisEmailDoesNotExist: 'Użytkownik o tym adresie Email nie istnieje',
  youNeedToVerifyEmail: 'Zweryfikuj email. Sprawdź pocztę lub spróbuj ponownie za 15 minut',
  incorrectLoginData: 'Błędne dane logowania',
  sessionExpired: 'Sesja wygasła',
  invalidAuthorizationKey: 'Proces autoryzacji został odrzucony',
  yourResetPasswordHasExpired: 'Twoja sesja dla resetu hasła wygasła. Spróbuj ponownie',
  incorrectOldPassword: 'Stare hasło nie jest poprawne',
  youMustProvideValidPasswordConfirmation: 'Musisz poprawnie powtórzyć hasło w celu weryfikacji',
  ' ': ' ',
  Serwisy: 'Serwisy',
  youHaveAlreadyVerifiedYourAccount: 'Zweryfikowałeś już swoje konto',
  userDoesNotExist: 'Użytkownik nie sitnieje',
  superAdmin: 'Super Administrator',
  admin: 'Administrator',
  user: 'Użytkownik',
  'Czas aktywnej sesji (min)': 'Czas aktywnej sesji (min)',
  login: 'Zaloguj się',
  welcome: 'Witaj',
  'Devices Quantity': 'Ilość urządzeń',
  'Blocked Devices': 'Zablokowane urządzenia',
  'Blocked IPs': 'Zablokowane adresy IP',
  userIsNotVerified: 'Użytkownik nie jest zweryfikowany',
  deviceVerified: 'Urządzenie zostało zweryfikowane',
  pleaseCheckYourEmailOrRetryAfter15minutes:
    'Zweryfikuj urządzenie. Sprawdź pocztę lub spróbuj ponownie za 15 minut',
  deviceAlreadyBlocked: 'Urządzenie jest już zablokowane',
  ipAlreadyBlocked: 'Adres IP został już zablokowany',
  updatedUserCouldNotBeFound: 'Użytkownik nie został znaleziony',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Reset hasła został już wysłany na pocztę email. Sprawdź pocztę lub odczekaj 15 minut i ponów próbę.',
  verificationFailed: 'Weryfikacja nie powiodła się',
  //komunikaty
  rowHasBeenUpdated: 'Zaktualizowano',
  setNewPassword: 'Podaj nowe hasło',
  emailsAreEqual: 'Email się powtarza',
  lastSignIn: 'Ostatnie logowanie',
  verifiedDevice: 'Zweryfikowane',
  yourPasswordHasBeenSuccessfullyChanged: 'Zmiana hasła zakończona powodzeniem',
  visitMailBoxAndConfirmPasswordReset: 'Użyj linku aktywacyjnego na swojej skrzynce email',
  passwordChanged: 'Hasło zostało zaktualizowane',
  passwordHasBeenChanged: 'Hasło zostało zaktualizowane',
  passwordHasBeenChangedDescription: 'Twoje dane uległy zmianie',
  confirmationEmailHasBeenSent: 'Zostało wysłane potwierdzenie email',
  //ciagi
  _Auth: 'Menadżer',
  _orizationManager: `autoryzacji`,
  userCreated: 'Użytkownik został dodany',

  //5-23-2024
  suppressSelfSecurityChanges: 'Wyłącz możliwość samoedycji ustawień bezpieczeństwa',
  suppressSelfSecurityChangesDescription:
    'Ta opcja będąc aktywowana spowoduje, że użytkownik nie będzie mógł konfigurować swoich ustawień bezpieczeństwa',
  verifyEmail: 'Zweryfikuj email',

  authorization: 'Autoryzacja',
  hostDistribution: 'Dystrybucja serwerów',
  editSelfAccount: 'Edycja konta',
  securitySettings: 'Ustawienia bezpieczeństwa',
  aboutQuarx: 'QUARX',
  HrTechnique: 'HRT',
  employeesList: 'Lista pracowników',
  employeeSpecifications: 'Cechowanie pracowników',
  employees: 'Pracownicy',
  employeesDescription: 'Ewidencja pracowników, cechowanie',
  specification: 'Cechowanie',
  dateOfBirth: 'Data urodzin',
  postcode: 'Kod pocztowy',
  userId: 'ID Autora',
  companies: 'Firmy',
  housingAssistant: 'Asystent zakwaterowania',
  recruiter: 'E-Rekruiter',
  documents: 'Dokumenty',
  integrations: 'Integracje',
  statistics: 'Statystyka',
  price: 'Cena',
  belongingProductsList: 'Lista produktów',
  productCategories: 'Kategorie produktów',
  productSpecifications: 'Cechowanie produktu',
  products: 'Produkty',
  productsDescription: 'Opis produktów',
  shelves: 'Półki',
  loans: 'Pożyczki',
  clients: 'Klienci',

  descriptionQuarx: 'QUARX (Qualified Unified Authorization and Resource eXchange -j.ang.)',
  descriptionQuarx1: 'To system autoryzacyjny dla systemów których dostawcą jest Web-Alchemy.',
  descriptionQuarx2:
    'Jest to niezależne rozwiązanie, które umozliwia dostęp do naszych usług w chmurze i zapewnia podstawową kontrolę ustawień bezpieczeństwa.',
  descriptionQuarx3:
    'Narzędzie umożliwia dostęp do aplikacji na podstawie udzielonych licencji, które można nabyć u dostawcy wraz z dedykowanym serwerem. Zależnie od ich zestawu użytkownik może korzystać z dostępnych usług.',
  descriptionQuarx4:
    'QUARX dostarcza również moduły statystyczne* i analizę danych ze zintegrowanych systemów',
  descriptionQuarx5:
    '* Rozwinięcie modułów opartych na analizie danych zostanie dostarczone w raz wersją 1.0Beta trylogii pierwszych systemów: QUARX, Lombandit i HRTechnique',

  authDescriptionQuarx:
    'Autoryzacja przez system QUARX skutecznie ogranicza dostęp niechcianych urządzeń, prowadząc ich ewidencję oraz umożliwiając konfigurację takich parametrów jak ograniczenia dostępu i blokady sieci oraz urządzeń. System pozwala także na wymuszanie autoryzacji nowych urządzeń, skracanie czasu aktywnej sesji oraz blokadę odświeżania sesji. Dzięki temu QUARX zapewnia wysoki poziom bezpieczeństwa i kontroli w rozproszonym środowisku, chroniąc zasoby przed nieuprawnionym dostępem.',
  authDescriptionQuarx1: '',
  authDescriptionQuarx2:
    'Dzięki systemowi QUARX możliwe jest jednoczesne obsługiwanie wielu aplikacji za pomocą jednego, centralnego konta QUARX. Umożliwia to zarządzanie wieloma biznesami w jednym miejscu, co znacznie ułatwia kontrolę i administrację różnych procesów.',
  authDescriptionQuarx3: '',
  authDescriptionQuarx4: '',
  authDescriptionQuarx5: '',

  licencesDescriptionQuarx:
    'Licencje uzyskuje się wraz z zakupem oprogramowania lub jako dodatek do posiadanych już produktów. Są one udzielane razem z dedykowanym serwerem, który jest dodatkowo zabezpieczony, aby zapewnić bezpośredni dostęp tylko dla klienta z użyciem VPN.',
  licencesDescriptionQuarx1: '',
  licencesDescriptionQuarx2: '',
  licencesDescriptionQuarx3: '',
  licencesDescriptionQuarx4: '',
  licencesDescriptionQuarx5: '',

  hostDescriptionQuarx:
    'Pracujemy na serwerach w chmurze u sprawdzonego dostawcy usług hostingowych. Jesteśmy elastyczni, więc dopasowujemy się do potrzeb klienta, oferując również usługi hostowane na serwerach fizycznych u samego klienta.',
  hostDescriptionQuarx1: '',
  hostDescriptionQuarx2: '',
  hostDescriptionQuarx3: '',
  hostDescriptionQuarx4: '',
  hostDescriptionQuarx5: '',

  usersDescriptionQuarx:
    'Administrator, czyli właściciel licencji, zyskuje dodatkowe uprawnienia oraz dostęp do zarządzania użytkownikami. W zależności od rozmiaru licencji, może przydzielić określoną liczbę kont dla swoich pracowników.',
  usersDescriptionQuarx1: '',
  usersDescriptionQuarx2:
    'W panelu "Zarządzanie kontami", administrator może przeprowadzić szereg inspekcji i konfiguracji bezpieczeństwa dla poszczególnych powiązanych kont. Narzędzie umożliwia menedżerowi wymuszenie autoryzacji nowych urządzeń poprzez email, skrócenie czasu sesji, wyłączenie odświeżania sesji oraz blokadę samodzielnego edytowania ustawień dla podległych kont.',
  usersDescriptionQuarx3:
    'Ten panel umożliwia również przypisanie posiadanych licencji do pozostałych kont oraz edycję danych personalnych użytkowników.',
  usersDescriptionQuarx4: '',
  usersDescriptionQuarx5: '',
  docs: 'Dokumentacja',

  securityDescriptionQuarx: '',
  securityDescriptionQuarx1:
    'Wymuszanie autoryzacji nowych urządzeń: Administrator może wymusić, aby każde nowe urządzenie próbujące uzyskać dostęp do systemu przeszło proces autoryzacji poprzez email. Zapewnia to, że tylko zweryfikowane urządzenia mają dostęp do zasobów',
  securityDescriptionQuarx2:
    'Skrócenie czasu sesji: Administrator może ustawić maksymalny czas trwania sesji użytkownika. Po upływie tego czasu użytkownik zostanie automatycznie wylogowany, co zwiększa bezpieczeństwo poprzez ograniczenie ryzyka dostępu do konta przez nieautoryzowane osoby.',
  securityDescriptionQuarx3:
    'Wyłączenie odświeżania sesji: Ta funkcja pozwala administratorowi zablokować automatyczne odświeżanie sesji, co zmusza użytkowników do ponownego logowania po zakończeniu sesji, zapewniając dodatkowy poziom kontroli dostępu.',
  securityDescriptionQuarx4:
    'Blokada autoedycji ustawień: Administrator może zablokować możliwość samodzielnego edytowania ustawień przez użytkowników podległych kont. Dzięki temu tylko administrator ma prawo do wprowadzania zmian w konfiguracjach, co zapobiega nieautoryzowanym modyfikacjom i zwiększa ogólne bezpieczeństwo systemu.',
  securityDescriptionQuarx5: '',
  aboutHrt: 'HRTechnique',
  aboutLombandit: 'Lombandit',
  lombanditDocs: 'Dokumentacja Lombandit',
  lombanditDocsDescription: 'Podstawowa wiedza o systemie',
  hrtDocs: 'Dokumentacja HRTechnique',
  hrtDocsDescription: 'Podstawowa wiedza o systemie',
  quarxDocs: 'Dokumentacja QUARX',
  quarxDocsDescription: 'Podstawowa wiedza o systemie',
  quarxEarly:
    '   QUARX jest w fazie wczesnego rozwoju. Spełnia podstawowe funkcje zawarte w dokumentacji. Funkcjonalność\n' +
    '          oznaczona *gwiazdką jest planowana na ostateczne wersje aplikacji, po pełnym wdrożeniu systemów HRTechnique i Lombandit.\n' +
    '       ',
  Docs: 'Dokumenty',
  QUARX: 'QUARX',
  Lombandit: 'Lombandit',
  HRTechniqe: 'HRTeqchnique',
  securityChart: 'Urządzenia',
  monthlyVisits: 'Top 5 ( ilośc wizyt w miesiącu )',
  monthlyActivities: 'Top 5 ( ilość aktywnośći w miesiącu )',
};
