export const en = {
  ownedLicences: 'List of authorized licenses',
  ownedLicencesDescription:
    'Access to other system applications can be obtained from the software provider',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Name',
  changePassword: 'Change password',
  editPersonalDetails: 'Edit your details',
  oldPassword: 'Old password',
  unlockAccount: 'Unlock account',
  newPassword: 'New password',
  confirmNewPassword: 'Confirm new password',
  reNewPassword: 'Confirm new password',
  accountBlocked: 'Account has been blocked',
  firstName: 'First Name',
  lastName: 'Last Name',
  language: 'Language',
  blockAccount: 'Block Account',
  personalId: 'Personal ID',
  email: 'Email',
  personalPhone: 'Personal Phone',
  city: 'City',
  postCode: 'Postal Code',
  description: 'Description',
  address: 'Address',
  noNotifications: 'No Notifications',
  notifications: 'Notifications',
  companyNip: 'Tax Identification Number (NIP)',
  companyName: 'Company Name',
  dashboard: 'Dashboard',
  submit: 'Submit',
  more: 'More',
  companyAddress: 'Company Address',
  companyPhone: 'Company Phone',
  'Welcome to': 'Welcome to',
  'Empower your company with the best solutions': 'Empower your company with the best solutions',
  'Distribution, Access, and Integration System': 'Distribution, Access, and Integration System',
  'System for Employment & Recruitment Agencies': 'System for Employment & Recruitment Agencies',
  'Pawn shop system & micro warehouse distribution':
    'Pawn shop system & micro warehouse distribution',
  'QUARX Manager': 'QUARX Manager',
  'Secure Authorization System for Your Solutions':
    'Secure Authorization System for Your Solutions',
  usersSecurity: 'User Security',
  services: 'Services',
  youCanAuthorizeFromHere: 'You can authorize from here',
  emailTaken: 'Email Taken',
  website: 'Website',
  search: 'Search',
  notifyUser: 'Notify User',
  sendNotification: 'Send Notification',
  send: 'Send',
  receivers: 'Receivers',
  devicesOnline: 'Devices Online',
  noSelectedUsers: 'No Selected Users',
  title: 'Title',
  code: 'Code',
  'title-code': 'Title (Code)',
  pleaseChooseReceiver: 'Please choose receivers',
  close: 'Close',
  saveChanges: 'Save Changes',
  id: 'ID Number',
  usersSecuritySettingsLevel: 'Security Settings Level',
  verified: 'Verified',
  actions: 'Actions',
  successfullySent: 'Sent Successfully',
  successfullySentDescription: 'Notification has been sent successfully',
  selected: 'Selected',
  devices: 'Devices',
  dashboardDescription: 'Global preview and statistics',
  networks: 'Networks',
  blockIpAddress: 'Block IP Address',
  blockDevice: 'Block Device',
  serverDown: 'Server Down',
  'Network error': 'Network Error',
  unlockIpAddress: 'Unlock IP Address',
  saveNewUser: 'Save New User',
  unlockDevice: 'Unlock Device',
  host: 'Host',
  licenceUserQty: 'Maximal users quantity',
  software: 'Software',
  licenceStart: 'Licence start',
  licenceEnd: 'Licence end',
  authorize: 'Authorize',
  resetPassword: 'Reset Password',
  editYourAccount: 'Edit Your Account',
  newVerificationEmailHasBeenSent: 'New verification email has been sent',
  editYourAccountDescription: 'Personal Data, Password Change, License Information',
  info: 'Information',
  account: 'Account',
  available: 'Available',
  permitted: 'Permitted',
  belongingUsersList: 'Users',
  create: 'Create New',
  signedDevices: 'Assigned Devices',
  signedDevicesDescription: 'List of devices user logged in from',
  newDeviceEmailVerification: 'New Device Email Verification',
  newDeviceEmailVerificationDescription:
    'Activating this function will require email confirmation for every new device user logs in from',
  turnedOn: 'On',
  turnedOff: 'Off',
  removeSelected: 'Remove Selected',
  verifyDevice: 'Verify Device',
  verifyDeviceAdmin: 'Mark as Verified',
  profile: 'Profile',
  licences: 'Licences',
  editAccount: 'Settings',
  sessionExpiry: 'Session Expiry Time (min)',
  validTo: 'Session Valid Until:',
  refreshIn: 'Refresh In:',
  refreshLocked: 'Locked',
  sessionExpiryDescription: 'You can shorten or extend the default session time',
  suppressTokenRefresh: 'Suppress Token Refresh',
  suppressTokenRefreshDescription:
    'Activating this function will prevent your session from refreshing after the required time, causing the session to expire after its duration',
  users: 'Users',
  emailHasBeenChanged: 'Email has been changed',
  usersManagement: 'User Management',
  signOut: 'Sign Out',
  youAreLoggedIn: 'You are logged in. Log out',
  usersManagementDescription: 'Edit personal data, Access configuration',
  manageUsers: 'Manage Users',
  tools: 'Tools',
  security: 'Security',
  "The session will refresh upon any activity if the user's online time exceeds":
    "The session will automatically refresh upon any activity if the user's online time exceeds",
  minutes: 'minutes',
  'and do not exceeds': 'and does not exceed',
  ip: 'IP',
  userAgent: 'User Agent',
  deviceStatus: 'Device Status',
  verificationLinkHasBeenSentToYourNewAddress:
    'Verification link has been sent to your new email address',
  off: 'Off',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Please check your new email for the link or retry after 15 minutes',
  incorrectPassword: 'Incorrect Password',
  online: 'Online',
  blockedDevice: 'Blocked Device',
  emptyRequiredFields: 'Required fields are empty',
  password: 'Password',
  newEmail: 'New Email',
  changeEmail: 'Change Email',

  // Errors
  cannotBanOwnerIpAddress: "Cannot ban owner's IP address",
  youCannotBlockOngoingDevice: 'You cannot block ongoing device',
  thisDeviceHasBeenBlocked: 'This device has been blocked',
  youMustFillAnEmail: 'You must fill in an email',
  youMustFillAPassword: 'You must fill in a password',
  blockedIp: 'Blocked IP',
  ipHasBeenBlocked: 'Your IP has been blocked',
  'Request failed with status code 400': 'Bad request',
  'Request failed with status code 303': 'Verification',
  userDoesNotBelongToTheAccount: 'User does not belong to the account',
  deviceDoesNotBelongToTheAccount: 'Device does not belong to the account',
  dataInvalidAuthorizationKey: 'Error reading authorization data',
  somethingGoneWrong: 'Something went wrong',
  noAuthorizationKeyProvided: 'No authorization data provided',
  userWithThisEmailDoesNotExist: 'User with this email does not exist',
  youNeedToVerifyEmail:
    'You need to verify your email. Check your inbox or try again in 15 minutes',
  incorrectLoginData: 'Incorrect login data',
  sessionExpired: 'Session expired',
  invalidAuthorizationKey: 'Authorization process rejected',
  yourResetPasswordHasExpired: 'Your password reset session has expired. Please try again',
  incorrectOldPassword: 'Incorrect old password',
  youMustProvideValidPasswordConfirmation: 'You must provide a valid password confirmation',
  ' ': ' ',
  polish: 'Polish',
  english: 'English',
  german: 'German',
  dutch: 'Dutch',
  Serwisy: 'Services',
  youHaveAlreadyVerifiedYourAccount: 'You have already verified your account',
  userDoesNotExist: 'User does not exist',
  superAdmin: 'Super Administrator',
  admin: 'Administrator',
  user: 'User',
  'Active session time (min)': 'Active session time (min)',
  login: 'Sign in',
  noLicenceOwned: 'Unavailability of the required licenses',
  welcome: 'Welcome',
  'Devices Quantity': 'Devices Quantity',
  'Blocked Devices': 'Blocked Devices',
  'Blocked IPs': 'Blocked IPs',
  userIsNotVerified: 'User is not verified',
  deviceVerified: 'Device has been verified',
  pleaseCheckYourEmailOrRetryAfter15minutes: 'Please check your email or retry after 15 minutes',
  deviceAlreadyBlocked: 'Device is already blocked',
  ipAlreadyBlocked: 'IP address is already blocked',
  updatedUserCouldNotBeFound: 'Updated user could not be found',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Password reset has already been sent to your email. Please check your email or retry after 15 minutes.',
  verificationFailed: 'Verification failed',
  // Messages
  rowHasBeenUpdated: 'Row has been updated',
  setNewPassword: 'Set new password',
  emailsAreEqual: 'Emails are equal',
  lastSignIn: 'Last sign-in',
  verifiedDevice: 'Verified Device',
  yourPasswordHasBeenSuccessfullyChanged: 'Your password has been successfully changed',
  visitMailBoxAndConfirmPasswordReset: 'Visit your mailbox and confirm password reset',
  passwordChanged: 'Password changed',
  passwordHasBeenChanged: 'Password has been changed',
  passwordHasBeenChangedDescription: 'Your data has been updated',
  confirmationEmailHasBeenSent: 'Confirmation email has been sent',
  userCreated: 'User has been created',

  //ciagi
  _Auth: 'Auth',
  _orizationManager: `Manager`,

  //5-23-2024
  suppressSelfSecurityChanges: 'Disable the ability to self-edit security settings',
  suppressSelfSecurityChangesDescription:
    'When this option is activated, the user will not be able to configure their security settings',
  verifyEmail: 'Verify email',
  _System:'System HR',
  _Lombard:'Hiring and Recruitment',
  employeesList:'Employees List',
  employeeSpecifications:'Employee Specifications',
  employees:'Employees',
  employeesDescription:'Employees Record, Specifications',
  specification:'Specification',
  dateOfBirth:'Date of Birth',
  postcode:'Postcode',
  userId:'User ID',
  companies:'Companies',
  housingAssistant:'Housing Assistant',
  recruiter:'E-Recruiter',
  documents:'Documents',
  integrations:'Integrations',
  statistics:'Statistics',
  signInWithKivi:'Sign In with Qivi'
};
