export const nl = {
  ownedLicences: 'Lijst van geautoriseerde licenties',
  ownedLicencesDescription:
    'Toegang tot andere systeemtoepassingen kunt u verkrijgen van de softwareleverancier',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Naam',
  changePassword: 'Wijzig wachtwoord',
  editPersonalDetails: 'Bewerk uw persoonlijke gegevens',
  oldPassword: 'Oud wachtwoord',
  unlockAccount: 'Ontgrendel account',
  newPassword: 'Nieuw wachtwoord',
  confirmNewPassword: 'Bevestig nieuw wachtwoord',
  reNewPassword: 'Bevestig nieuw wachtwoord',
  accountBlocked: 'Account is geblokkeerd',
  firstName: 'Voornaam',
  lastName: 'Achternaam',
  language: 'Taal',
  blockAccount: 'Blokkeren account',
  personalId: 'Persoonlijk identificatienummer',
  email: 'E-mail',
  personalPhone: 'Persoonlijk telefoonnummer',
  city: 'Stad',
  postCode: 'Postcode',
  description: 'Beschrijving',
  address: 'Adres',
  noNotifications: 'Geen meldingen',
  'Welcome to': 'Welkom bij',
  'Empower your company with the best solutions': 'Versterk uw bedrijf met de beste oplossingen',
  notifications: 'Meldingen',
  companyNip: 'Belastingnummer',
  'Distribution, Access, and Integration System': 'Distributie-, toegangs- en integratiesysteem',
  'System for Employment & Recruitment Agencies': 'Systeem voor Arbeids- en Wervingsbureaus',
  'Pawn shop system & micro warehouse distribution': 'Pandjessysteem & micro-opslag distributie',
  'QUARX Manager': 'QUARX Manager',
  more: 'Meer',
  'Secure Authorization System for Your Solutions':
    'Beveiligd autorisatiesysteem voor uw oplossingen',
  submit: 'Verzenden',
  companyName: 'Bedrijfsnaam',
  dashboard: 'Dashboard',
  companyAddress: 'Bedrijfsadres',
  'Page Size:': 'Paginagrootte:',
  pageSizeSelectorLabel: 'Paginagrootte:',
  dashboardDescription: 'Overzicht van wijzigingen, algemene statistieken',
  host: 'Host',
  authorize: 'Autoriseren',
  licenceUserQty: 'Maximaal aantal gelicentieerde gebruikers',
  newVerificationEmailHasBeenSent: 'Nieuwe verificatie-e-mail is verzonden',
  software: 'Software',
  licenceStart: 'Start licentieperiode',
  licenceEnd: 'Einde licentieperiode',
  companyPhone: 'Bedrijfstelefoon',
  usersSecurity: 'Gebruikersbeveiliging',
  services: 'Diensten',
  youCanAuthorizeFromHere: 'U kunt hier autoriseren',
  emailTaken: 'E-mail bezet',
  website: 'Website',
  search: 'Zoeken',
  notifyUser: 'Gebruiker op de hoogte stellen',
  sendNotification: 'Notificatie verzenden',
  send: 'Verzenden',
  receivers: 'Ontvangers',
  devicesOnline: 'Apparaten online',
  noSelectedUsers: 'Geen geselecteerde gebruikers',
  title: 'Titel',
  code: 'Code',
  'title-code': 'Titel (Code)',
  pleaseChooseReceiver: 'Selecteer gebruikers om ontvangers te kiezen',
  close: 'Sluiten',
  saveChanges: 'Wijzigingen opslaan',
  id: 'ID-nummer',
  usersSecuritySettingsLevel: 'Beveiligingsniveau gebruikers',
  verified: 'Geverifieerd',
  actions: 'Acties',
  successfullySent: 'Succesvol verzonden',
  successfullySentDescription: 'Notificatie is succesvol verzonden',
  selected: 'Geselecteerd',
  devices: 'Apparaten',
  networks: 'Netwerken',
  blockIpAddress: 'IP-adres blokkeren',
  blockDevice: 'Apparaat blokkeren',
  serverDown: 'Server niet beschikbaar',
  'Network error': 'Netwerkfout',
  unlockIpAddress: 'IP-adres deblokkeren',
  saveNewUser: 'Nieuwe gebruiker opslaan',
  unlockDevice: 'Apparaat deblokkeren',
  resetPassword: 'Wachtwoord resetten',
  editYourAccount: 'Accountinstellingen bewerken',
  editYourAccountDescription: 'Persoonlijke gegevens, wachtwoord wijzigen, licentiegegevens',
  info: 'Informatie',
  account: 'Account',
  available: 'Beschikbaar',
  permitted: 'Toegestaan',
  polish: 'Pools',
  english: 'Engels',
  german: 'Duits',
  dutch: 'Nederlands',
  belongingUsersList: 'Lijst met bijbehorende gebruikers',
  noLicenceOwned: 'Geen licenties in bezit',
  create: 'Nieuw aanmaken',
  signedDevices: 'Ondertekende apparaten',
  signedDevicesDescription: 'Lijst van apparaten waarop de gebruiker is ingelogd',
  newDeviceEmailVerification: 'E-mailverificatie voor nieuwe apparaten',
  newDeviceEmailVerificationDescription:
    'Door deze functie te activeren, vereist elk nieuw apparaat waarop de gebruiker inlogt een bevestiging via e-mail',
  turnedOn: 'Ingeschakeld',
  turnedOff: 'Uitgeschakeld',
  removeSelected: 'Geselecteerde verwijderen',
  verifyDevice: 'Apparaat verifiëren',
  verifyDeviceAdmin: 'Instellen als geverifieerd',
  profile: 'Profiel',
  licences: 'Licenties',
  editAccount: 'Account bewerken',
  sessionExpiry: 'Sessie verlooptijd (min)',
  validTo: 'Geldig tot:',
  refreshIn: 'Vernieuwen in:',
  refreshLocked: 'Vernieuwing geblokkeerd',
  sessionExpiryDescription: 'U kunt de standaard sessieduur verkorten of verlengen',
  suppressTokenRefresh: 'Vernieuwing van tokens onderdrukken',
  suppressTokenRefreshDescription:
    'Als deze functie is ingeschakeld, wordt uw sessie niet vernieuwd na de ingestelde tijd, wat resulteert in het verlopen van de sessie',
  users: 'Gebruikers',
  emailHasBeenChanged: 'E-mail is gewijzigd',
  usersManagement: 'Gebruikersbeheer',
  signOut: 'Afmelden',
  youAreLoggedIn: 'U bent ingelogd.',
  usersManagementDescription: 'Bewerken van persoonlijke gegevens, toegangsconfiguratie',
  manageUsers: 'Beheer gebruikers',
  tools: 'Tools',
  security: 'Veiligheid',
  "The session will refresh upon any activity if the user's online time exceeds":
    'De sessie wordt vernieuwd bij elke activiteit als de online tijd van de gebruiker de limiet overschrijdt',
  minutes: 'minuten',
  'and do not exceeds': 'en overschrijdt niet',
  ip: 'IP',
  userAgent: 'Apparaat',
  deviceStatus: 'Apparaatstatus',
  verificationLinkHasBeenSentToYourNewAddress:
    'Verificatielink is verzonden naar uw nieuwe e-mailadres',
  off: 'Uitgeschakeld',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Controleer uw nieuwe e-mail voor de link of probeer het na 15 minuten opnieuw',
  incorrectPassword: 'Onjuist wachtwoord',
  online: 'Online',
  blockedDevice: 'Geblokkeerd apparaat',
  emptyRequiredFields: 'Verplichte velden zijn leeg',
  password: 'Wachtwoord',
  newEmail: 'Nieuwe e-mail',
  changeEmail: 'Verander e-mailadres',

  // fouten
  cannotBanOwnerIpAddress: 'Kan het huidige IP-adres van de eigenaar niet blokkeren',
  youCannotBlockOngoingDevice: 'U kunt het huidige apparaat niet blokkeren',
  thisDeviceHasBeenBlocked: 'Dit apparaat is geblokkeerd',
  youMustFillAnEmail: 'U moet een e-mailadres invullen',
  youMustFillAPassword: 'U moet een wachtwoord invullen',
  blockedIp: 'Geblokkeerd IP-adres',
  ipHasBeenBlocked: 'Uw IP-adres is geblokkeerd',
  'Request failed with status code 400': 'Foutief verzoek met statuscode 400',
  'Request failed with status code 303': 'Verificatie',
  userDoesNotBelongToTheAccount: 'Gebruiker behoort niet tot uw account',
  deviceDoesNotBelongToTheAccount: 'Apparaat behoort niet tot het account',
  dataInvalidAuthorizationKey: 'Ongeldige autorisatiesleutel',
  somethingGoneWrong: 'Er is iets misgegaan',
  noAuthorizationKeyProvided: 'Geen autorisatiesleutel verstrekt',
  userWithThisEmailDoesNotExist: 'Gebruiker met dit e-mailadres bestaat niet',
  youNeedToVerifyEmail:
    'Verifieer e-mail. Controleer uw inbox of probeer het opnieuw over 15 minuten',
  incorrectLoginData: 'Onjuiste inloggegevens',
  sessionExpired: 'Sessie verlopen',
  invalidAuthorizationKey: 'Ongeldige autorisatiesleutel',
  yourResetPasswordHasExpired: 'Uw wachtwoordreset-sessie is verlopen. Probeer het opnieuw',
  incorrectOldPassword: 'Oud wachtwoord is onjuist',
  youMustProvideValidPasswordConfirmation:
    'U moet het wachtwoord correct herhalen om te bevestigen',
  ' ': ' ',
  Serwisy: 'Diensten',
  youHaveAlreadyVerifiedYourAccount: 'Je hebt je account al geverifieerd',
  userDoesNotExist: 'Gebruiker bestaat niet',
  superAdmin: 'Superbeheerder',
  admin: 'Beheerder',
  user: 'Gebruiker',
  'Czas aktywnej sesji (min)': 'Actieve sessietijd (min)',
  login: 'Inloggen',
  welcome: 'Welkom',
  'Devices Quantity': 'Aantal apparaten',
  'Blocked Devices': 'Geblokkeerde apparaten',
  'Blocked IPs': 'Geblokkeerde IP-adressen',
  userIsNotVerified: 'Gebruiker is niet geverifieerd',
  deviceVerified: 'Apparaat is geverifieerd',
  pleaseCheckYourEmailOrRetryAfter15minutes:
    'Controleer uw e-mail of probeer het opnieuw na 15 minuten',
  deviceAlreadyBlocked: 'Apparaat is al geblokkeerd',
  ipAlreadyBlocked: 'IP-adres is al geblokkeerd',
  updatedUserCouldNotBeFound: 'Gebruiker kon niet worden gevonden',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Reset wachtwoord is al naar uw e-mail verzonden. Controleer uw e-mail of probeer het opnieuw na 15 minuten.',
  verificationFailed: 'Verificatie mislukt',
  rowHasBeenUpdated: 'Rij is bijgewerkt',
  setNewPassword: 'Stel een nieuw wachtwoord in',
  emailsAreEqual: 'E-mails zijn gelijk',
  lastSignIn: 'Laatste aanmelding',
  verifiedDevice: 'Geverifieerd apparaat',
  yourPasswordHasBeenSuccessfullyChanged: 'Uw wachtwoord is succesvol gewijzigd',
  visitMailBoxAndConfirmPasswordReset: 'Ga naar uw postvak en bevestig het wachtwoordherstel',
  passwordChanged: 'Wachtwoord is gewijzigd',
  passwordHasBeenChanged: 'Wachtwoord is gewijzigd',
  passwordHasBeenChangedDescription: 'Uw gegevens zijn gewijzigd',
  confirmationEmailHasBeenSent: 'Bevestigingsmail is verzonden',
  _Auth: 'Authenticatie',
  _orizationManager: 'autorisatiemanager',
  userCreated: 'Gebruiker is toegevoegd',

  //25.05
  suppressSelfSecurityChanges: 'Schakel de mogelijkheid om beveiligingsinstellingen zelf te wijzigen uit',
  suppressSelfSecurityChangesDescription:
    'Wanneer deze optie is geactiveerd, kan de gebruiker zijn beveiligingsinstellingen niet configureren',
  verifyEmail: 'Verifieer e-mail',
  _System:'HR-systeem',
  _Lombard:'Werving en tewerkstelling',
  employeesList:'Employees List',
  employeeSpecifications:'Employee Specifications',
  employees:'Employees',
  employeesDescription:'Employees Record, Specifications',
  specification:'Specification',
  dateOfBirth:'Date of Birth',
  postcode:'Postcode',
  userId:'User ID',
  companies:'Bedrijven',
  housingAssistant:'Huisvestingsassistent',
  recruiter:'E-Recruiter',
  documents:'Documenten',
  integrations:'Integraties',
  statistics:'Statistieken'
};
