export const pl = {
  ownedLicences: 'Lista autoryzowanych licencji',
  ownedLicencesDescription:
    'Dostęp do innych aplikacji systemu możesz uzyskać od dostawcy oprogramowania',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Nazwa',
  changePassword: 'Zmień hasło',
  editPersonalDetails: 'Edytuj swoje dane',
  oldPassword: 'Stare hasło',
  unlockAccount: 'Odblokuj konto',
  newPassword: 'Nowe hasło',
  confirmNewPassword: 'Potwierdź nowe hasło',
  reNewPassword: 'Potwierdź nowe hasło',
  accountBlocked: 'Konto zostało zablokowane',
  firstName: 'Imię',
  lastName: 'Nazwisko',
  language: 'Język',
  blockAccount: 'Zablokuj konto',
  personalId: 'Pesel',
  email: 'Email',
  personalPhone: 'Telefon prywatny',
  city: 'Miasto',
  postCode: 'Kod pocztowy',
  description: 'Opis',
  address: 'Adres',
  noNotifications: 'Brak powiadomień',
  'Welcome to': 'Witaj w',
  'Empower your company with the best solutions': 'Wzmocnij swoją firmę najlepszymi rozwiązaniami',
  notifications: 'Powiadomienia',
  companyNip: 'Nip',
  'Distribution, Access, and Integration System': 'System Dystrybucji, Dostępu i Integracji',
  'System for Employment & Recruitment Agencies': 'System dla Agencji Zatrudnienia i Rekruterów',
  'Pawn shop system & micro warehouse distribution': 'System dla lombardów i mikromagazynów',
  'QUARX Manager': 'QUARX Menadżer',
  more: 'Więcej',
  'Secure Authorization System for Your Solutions':
    'Bezpieczny system autoryzacyjny dla twoich rozwiązań',
  submit: 'Zatwierdź',
  companyName: 'Nazwa firmy',
  dashboard: 'Panel',
  companyAddress: 'Adres firmy',
  'Page Size:': 'Ilość na stronę',
  pageSizeSelectorLabel: 'Ilość na stronę',
  dashboardDescription: 'Podgląd zmian, statystyka ogólna',
  host: 'Host',
  authorize: 'Autoryzacja',
  licenceUserQty: 'Maksymalna liczba licencjonwanych użytkowników',
  newVerificationEmailHasBeenSent: 'Nowy email weryfikacyjny został wysłany',
  software: 'Oprogramowanie',
  licenceStart: 'Czas rozpoczęcia licencji',
  licenceEnd: 'Czas zakończenia licencji',
  companyPhone: 'Telefon służbowy',
  usersSecurity: 'Podgląd',
  services: 'Serwisy',
  youCanAuthorizeFromHere: 'Możesz się stąd autoryzować',
  emailTaken: 'Email zajęty',
  website: 'Adres www',
  search: 'Szukaj',
  notifyUser: 'Wyślij powiadomienie',
  sendNotification: 'Wyślij powiadomienie',
  send: 'Prześlij',
  receivers: 'Odbiorcy',
  devicesOnline: 'Urządzenia online',
  noSelectedUsers: 'Brak wybranych odbiorców',
  title: 'Tytuł',
  code: 'Kod',
  'title-code': 'Tytuł (Kod)',
  pleaseChooseReceiver: 'Zaznacz użytkowników aby wybrać odbiorców',
  close: 'Zamknij',
  saveChanges: 'Zapisz zmiany',
  id: 'Numer ID',
  usersSecuritySettingsLevel: 'Poziom bezpieczeństwa',
  verified: 'Zweryfikowany',
  actions: 'Zaawansowane',
  successfullySent: 'Wysłano',
  successfullySentDescription: 'Powiadomienie zostało przesłane z powodzeniem',
  selected: 'Wybrane',
  devices: 'Urządzenia',
  networks: 'Sieć',
  blockIpAddress: 'Zablokuj adres IP',
  blockDevice: 'Zablokuj urządzenie',
  serverDown: 'Serwer nie odpowiada',
  'Network error': 'Błąd połaczenia',
  unlockIpAddress: 'Odblokuj adres IP',
  saveNewUser: 'Zapisz',
  unlockDevice: 'Oblokuj urządzenie',
  resetPassword: 'Reset hasła',
  editYourAccount: 'Ustawienia konta',
  editYourAccountDescription: 'Dane osobowe, zmiana hasła, informacje o licencjach',
  info: 'Informacje',
  account: 'Konto',
  available: 'Dostępne',
  permitted: 'Przydzielone',
  polish: 'Polski',
  english: 'Angielski',
  german: 'Niemiecki',
  dutch: 'Niderlandzki',
  belongingUsersList: 'Użytkownicy',
  noLicenceOwned: 'Brak posiadanych licencji',
  create: 'Stwórz nowy',
  signedDevices: 'Przypisane urządzenia',
  signedDevicesDescription: 'Lista urządzeń na których loguje się użytkownik',
  newDeviceEmailVerification: 'Weryfikacja urządzeń przez Email',
  newDeviceEmailVerificationDescription:
    'Aktywyjąc tą funkcję każde nowe urządzenie, z którego loguje się użytkownik, będzie wymagało potwierdzenia przez pocztę email',
  turnedOn: 'Aktywowane',
  turnedOff: 'Dezaktywowane',
  removeSelected: 'Usuń zaznaczone',
  verifyDevice: 'Zweryfikuj urządzenie',
  verifyDeviceAdmin: 'Ustaw jako zweryfikowane',
  profile: 'Profil',
  licences: 'Licencje',
  editAccount: 'Ustawienia',
  sessionExpiry: 'Czas aktywnej sesji (min)',
  validTo: 'Sesja aktywna do:',
  refreshIn: 'Odświeżenie za:',
  refreshLocked: 'Wyłączono',
  sessionExpiryDescription: 'Moźesz skrócić lub przedłużyć domyślny czas sesji',
  suppressTokenRefresh: 'Wyłącz odnawianie sesji',
  suppressTokenRefreshDescription:
    'Ta funkcja uruchomiona spowoduje, że twoja sesja nie będzie się odnawiać po wymaganym czasie. Spowoduje to wygaśnięcie sesji po czasie jej trawnia',
  users: 'Użytkownicy',
  emailHasBeenChanged: 'Email został zmieniony',
  usersManagement: 'Zarządzanie użytkownikami',
  signOut: 'Wyloguj',
  youAreLoggedIn: 'Wyloguj sie.',
  usersManagementDescription: 'Edycja danych osobowych, Konfiguracja dostępu',
  manageUsers: 'Zarządzanie',
  tools: 'Narzędzia',
  security: 'Bezpieczeństwo',
  "The session will refresh upon any activity if the user's online time exceeds":
    'Sesja odnowi się automatycznie podczas aktywności jeśli czas zalogowania użytkownika przeczoczy',
  minutes: 'minut',
  'and do not exceeds': 'i nie przekroczy',
  ip: 'IP',
  userAgent: 'Urządzenie',
  deviceStatus: 'Status urządzenia',
  verificationLinkHasBeenSentToYourNewAddress: 'Link weryfikacyjny został wysłany na nowy email',
  off: 'Wygaszony',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Wykorzystaj link wysłany na nowy adres, lub odczekaj 15 minut i spróbuj znowu',
  incorrectPassword: 'Niepoprawne hasło',
  online: 'Aktywny',
  blockedDevice: 'Zablokowane urządzenie',
  emptyRequiredFields: 'Wymagane pola są puste',
  password: 'Hasło',
  newEmail: 'Nowy email',
  changeEmail: 'Zmień adres Email',

  //bledy
  cannotBanOwnerIpAddress: 'Nie można zbanować bieżącego adresu IP',
  youCannotBlockOngoingDevice: 'Nie można zbanować bieżącego urządzenia',
  thisDeviceHasBeenBlocked: 'Urządznie zostało zablokowane',
  youMustFillAnEmail: 'Wypełnij polę Email',
  youMustFillAPassword: 'Wypełnij pole hasło',
  blockedIp: 'Zablokowana sieć',
  ipHasBeenBlocked: 'Twoja sieć została zablokowana',
  'Request failed with status code 400': 'Błędne żądanie',
  'Request failed with status code 303': 'Weryfikacja',
  userDoesNotBelongToTheAccount: 'Użytkownik nie należy do twojego konta',
  deviceDoesNotBelongToTheAccount: 'Urządzenie nie należy do konta',
  dataInvalidAuthorizationKey: 'Błąd z odczytem danych autoryzacji',
  somethingGoneWrong: 'Coś poszło nie tak',
  noAuthorizationKeyProvided: 'Nie dostarczono danych autoryzacyjnych',
  userWithThisEmailDoesNotExist: 'Użytkownik o tym adresie Email nie istnieje',
  youNeedToVerifyEmail: 'Zweryfikuj email. Sprawdź pocztę lub spróbuj ponownie za 15 minut',
  incorrectLoginData: 'Błędne dane logowania',
  sessionExpired: 'Sesja wygasła',
  invalidAuthorizationKey: 'Proces autoryzacji został odrzucony',
  yourResetPasswordHasExpired: 'Twoja sesja dla resetu hasła wygasła. Spróbuj ponownie',
  incorrectOldPassword: 'Stare hasło nie jest poprawne',
  youMustProvideValidPasswordConfirmation: 'Musisz poprawnie powtórzyć hasło w celu weryfikacji',
  ' ': ' ',
  Serwisy: 'Serwisy',
  youHaveAlreadyVerifiedYourAccount: 'Zweryfikowałeś już swoje konto',
  userDoesNotExist: 'Użytkownik nie sitnieje',
  superAdmin: 'Super Administrator',
  admin: 'Administrator',
  user: 'Użytkownik',
  'Czas aktywnej sesji (min)': 'Czas aktywnej sesji (min)',
  login: 'Zaloguj się',
  welcome: 'Witaj',
  'Devices Quantity': 'Ilość urządzeń',
  'Blocked Devices': 'Zablokowane urządzenia',
  'Blocked IPs': 'Zablokowane adresy IP',
  userIsNotVerified: 'Użytkownik nie jest zweryfikowany',
  deviceVerified: 'Urządzenie zostało zweryfikowane',
  pleaseCheckYourEmailOrRetryAfter15minutes:
    'Zweryfikuj urządzenie. Sprawdź pocztę lub spróbuj ponownie za 15 minut',
  deviceAlreadyBlocked: 'Urządzenie jest już zablokowane',
  ipAlreadyBlocked: 'Adres IP został już zablokowany',
  updatedUserCouldNotBeFound: 'Użytkownik nie został znaleziony',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Reset hasła został już wysłany na pocztę email. Sprawdź pocztę lub odczekaj 15 minut i ponów próbę.',
  verificationFailed: 'Weryfikacja nie powiodła się',
  //komunikaty
  rowHasBeenUpdated: 'Zaktualizowano',
  setNewPassword: 'Podaj nowe hasło',
  emailsAreEqual: 'Email się powtarza',
  lastSignIn: 'Ostatnie logowanie',
  verifiedDevice: 'Zweryfikowane',
  yourPasswordHasBeenSuccessfullyChanged: 'Zmiana hasła zakończona powodzeniem',
  visitMailBoxAndConfirmPasswordReset: 'Użyj linku aktywacyjnego na swojej skrzynce email',
  passwordChanged: 'Hasło zostało zaktualizowane',
  passwordHasBeenChanged: 'Hasło zostało zaktualizowane',
  passwordHasBeenChangedDescription: 'Twoje dane uległy zmianie',
  confirmationEmailHasBeenSent: 'Zostało wysłane potwierdzenie email',
  //ciagi
  _Auth: 'Menadżer',
  _orizationManager: `autoryzacji`,
  userCreated: 'Użytkownik został dodany',

  //5-23-2024
  suppressSelfSecurityChanges: 'Wyłącz możliwość samoedycji ustawień bezpieczeństwa',
  suppressSelfSecurityChangesDescription:
    'Ta opcja będąc aktywowana spowoduje, że użytkownik nie będzie mógł konfigurować swoich ustawień bezpieczeństwa',
  verifyEmail: 'Zweryfikuj email',
  _System:'System HR',
  _Lombard:'zatrudnienie i rekrutacja',

  //Lombandit
  price:'Cena',
  belongingProductsList:'Lista produktów',

  //HRTechnique
  employeesList:'Lista pracowników',
  employeeSpecifications:'Cechowanie pracowników',
  employees:'Pracownicy',
  employeesDescription:'Ewidencja pracowników, cechowanie',
  specification:'Cechowanie',
  dateOfBirth:'Data urodzin',
  postcode:'Kod pocztowy',
  userId:'ID Autora',
  companies:'Firmy',
  housingAssistant:'Asystent zakwaterowania',
  recruiter:'E-Rekruiter',
  documents:'Dokumenty',
  integrations:'Integracje',
  statistics:'Statystyka',
  signInWithKivi:'Zaloguj się z Qivi'
};
