export const de = {
  ownedLicences: 'Liste der autorisierten Lizenzen',
  ownedLicencesDescription:
    'Zugriff auf andere Systemanwendungen können Sie vom Softwareanbieter erhalten',
  hrtLicence: 'HRTechnique',
  lombanditLicence: 'Lombandit',
  name: 'Name',
  changePassword: 'Passwort ändern',
  editPersonalDetails: 'Persönliche Daten bearbeiten',
  oldPassword: 'Altes Passwort',
  unlockAccount: 'Konto entsperren',
  newPassword: 'Neues Passwort',
  confirmNewPassword: 'Neues Passwort bestätigen',
  reNewPassword: 'Neues Passwort bestätigen',
  accountBlocked: 'Konto wurde gesperrt',
  firstName: 'Vorname',
  lastName: 'Nachname',
  language: 'Sprache',
  blockAccount: 'Konto sperren',
  personalId: 'Pesel',
  email: 'E-Mail',
  personalPhone: 'Private Telefonnummer',
  city: 'Stadt',
  postCode: 'Postleitzahl',
  description: 'Beschreibung',
  address: 'Adresse',
  noNotifications: 'Keine Benachrichtigungen',
  'Welcome to': 'Willkommen bei',
  'Empower your company with the best solutions':
    'Stärken Sie Ihr Unternehmen mit den besten Lösungen',
  notifications: 'Benachrichtigungen',
  companyNip: 'NIP',
  'Distribution, Access, and Integration System': 'Verteilungs-, Zugriffs- und Integrationssystem',
  'System for Employment & Recruitment Agencies':
    'System für Arbeits- und Personalvermittlungsagenturen',
  'Pawn shop system & micro warehouse distribution':
    'System für Pfandhäuser und Mikrolagervertrieb',
  'QUARX Manager': 'QUARX Manager',
  more: 'Mehr',
  'Secure Authorization System for Your Solutions':
    'Sicheres Autorisierungssystem für Ihre Lösungen',
  submit: 'Bestätigen',
  companyName: 'Firmenname',
  dashboard: 'Dashboard',
  companyAddress: 'Firmenadresse',
  'Page Size:': 'Seitengröße:',
  pageSizeSelectorLabel: 'Seitengröße',
  dashboardDescription: 'Übersicht der Änderungen, allgemeine Statistik',
  host: 'Host',
  authorize: 'Autorisieren',
  licenceUserQty: 'Maximale Anzahl lizenzierter Benutzer',
  newVerificationEmailHasBeenSent: 'Neue Bestätigungs-E-Mail wurde gesendet',
  software: 'Software',
  licenceStart: 'Lizenzbeginn',
  licenceEnd: 'Lizenzende',
  companyPhone: 'Firmentelefon',
  usersSecurity: 'Übersicht',
  services: 'Dienste',
  youCanAuthorizeFromHere: 'Sie können sich von hier aus autorisieren',
  emailTaken: 'E-Mail bereits vergeben',
  website: 'Webseite',
  search: 'Suchen',
  notifyUser: 'Benutzer benachrichtigen',
  sendNotification: 'Benachrichtigung senden',
  send: 'Senden',
  receivers: 'Empfänger',
  devicesOnline: 'Geräte online',
  noSelectedUsers: 'Keine ausgewählten Empfänger',
  title: 'Titel',
  code: 'Code',
  'title-code': 'Titel (Code)',
  pleaseChooseReceiver: 'Wählen Sie Benutzer, um Empfänger auszuwählen',
  close: 'Schließen',
  saveChanges: 'Änderungen speichern',
  id: 'ID-Nummer',
  usersSecuritySettingsLevel: 'Sicherheitsstufe',
  verified: 'Verifiziert',
  actions: 'Aktionen',
  successfullySent: 'Erfolgreich gesendet',
  successfullySentDescription: 'Benachrichtigung wurde erfolgreich gesendet',
  selected: 'Ausgewählt',
  devices: 'Geräte',
  networks: 'Netzwerke',
  blockIpAddress: 'IP-Adresse sperren',
  blockDevice: 'Gerät sperren',
  serverDown: 'Server nicht erreichbar',
  'Network error': 'Netzwerkfehler',
  unlockIpAddress: 'IP-Adresse entsperren',
  saveNewUser: 'Speichern',
  unlockDevice: 'Gerät entsperren',
  resetPassword: 'Passwort zurücksetzen',
  editYourAccount: 'Kontoeinstellungen',
  editYourAccountDescription: 'Persönliche Daten, Passwort ändern, Lizenzinformationen',
  info: 'Informationen',
  account: 'Konto',
  available: 'Verfügbar',
  permitted: 'Zugewiesen',
  polish: 'Polnisch',
  english: 'Englisch',
  german: 'Deutsch',
  dutch: 'Niederländisch',
  belongingUsersList: 'Benutzer',
  noLicenceOwned: 'Keine Lizenzen vorhanden',
  create: 'Neu erstellen',
  signedDevices: 'Zugewiesene Geräte',
  signedDevicesDescription: 'Liste der Geräte, auf denen sich der Benutzer anmeldet',
  newDeviceEmailVerification: 'Geräteverifizierung per E-Mail',
  newDeviceEmailVerificationDescription:
    'Aktivieren Sie diese Funktion, um jedes neue Gerät, von dem sich der Benutzer anmeldet, per E-Mail zu bestätigen',
  turnedOn: 'Aktiviert',
  turnedOff: 'Deaktiviert',
  removeSelected: 'Ausgewählte entfernen',
  verifyDevice: 'Gerät verifizieren',
  verifyDeviceAdmin: 'Als verifiziert festlegen',
  profile: 'Profil',
  licences: 'Lizenzen',
  editAccount: 'Einstellungen',
  sessionExpiry: 'Sitzungsdauer (Minuten)',
  validTo: 'Sitzung aktiv bis:',
  refreshIn: 'Aktualisierung in:',
  refreshLocked: 'Deaktiviert',
  sessionExpiryDescription: 'Sie können die standardmäßige Sitzungsdauer verkürzen oder verlängern',
  suppressTokenRefresh: 'Sitzungserneuerung deaktivieren',
  suppressTokenRefreshDescription:
    'Wenn diese Funktion aktiviert ist, wird Ihre Sitzung nach der erforderlichen Zeit nicht erneuert. Dies führt zum Ablauf der Sitzung nach deren Dauer.',
  users: 'Benutzer',
  emailHasBeenChanged: 'E-Mail wurde geändert',
  usersManagement: 'Benutzerverwaltung',
  signOut: 'Abmelden',
  youAreLoggedIn: 'Sie sind eingeloggt.',
  usersManagementDescription: 'Bearbeitung persönlicher Daten, Zugriffskonfiguration',
  manageUsers: 'Verwalten',
  tools: 'Werkzeuge',
  security: 'Sicherheit',
  "The session will refresh upon any activity if the user's online time exceeds":
    'Die Sitzung wird bei jeglicher Aktivität automatisch erneuert, wenn die Online-Zeit des Benutzers überschreitet',
  minutes: 'Minuten',
  'and do not exceeds': 'und nicht überschreitet',
  ip: 'IP',
  userAgent: 'Gerät',
  deviceStatus: 'Gerätestatus',
  verificationLinkHasBeenSentToYourNewAddress:
    'Ein Bestätigungslink wurde an Ihre neue E-Mail-Adresse gesendet',
  off: 'Deaktiviert',
  pleaseCheckYourNewEmailForLinkOrRetryAfter2hours:
    'Nutzen Sie den Link, der an die neue Adresse gesendet wurde, oder warten Sie 15 Minuten und versuchen Sie es erneut',
  incorrectPassword: 'Falsches Passwort',
  online: 'Aktiv',
  blockedDevice: 'Gesperrtes Gerät',
  emptyRequiredFields: 'Erforderliche Felder sind leer',
  password: 'Passwort',
  newEmail: 'Neue E-Mail',
  changeEmail: 'E-Mail-Adresse ändern',

  // Fehler
  cannotBanOwnerIpAddress: 'Die aktuelle IP-Adresse kann nicht gesperrt werden',
  youCannotBlockOngoingDevice: 'Das aktuelle Gerät kann nicht gesperrt werden',
  thisDeviceHasBeenBlocked: 'Dieses Gerät wurde gesperrt',
  youMustFillAnEmail: 'Bitte füllen Sie das E-Mail-Feld aus',
  youMustFillAPassword: 'Bitte füllen Sie das Passwort-Feld aus',
  blockedIp: 'Netzwerk gesperrt',
  ipHasBeenBlocked: 'Ihr Netzwerk wurde gesperrt',
  'Request failed with status code 400': 'Fehlerhafte Anfrage',
  'Request failed with status code 303': 'Überprüfung erforderlich',
  userDoesNotBelongToTheAccount: 'Benutzer gehört nicht zu Ihrem Konto',
  deviceDoesNotBelongToTheAccount: 'Gerät gehört nicht zu Ihrem Konto',
  dataInvalidAuthorizationKey: 'Fehler beim Auslesen der Autorisierungsdaten',
  somethingGoneWrong: 'Etwas ist schiefgelaufen',
  noAuthorizationKeyProvided: 'Keine Autorisierungsdaten bereitgestellt',
  userWithThisEmailDoesNotExist: 'Ein Benutzer mit dieser E-Mail-Adresse existiert nicht',
  youNeedToVerifyEmail:
    'Bitte verifizieren Sie Ihre E-Mail. Überprüfen Sie Ihr Postfach oder versuchen Sie es in 15 Minuten erneut',
  incorrectLoginData: 'Falsche Anmeldedaten',
  sessionExpired: 'Sitzung abgelaufen',
  invalidAuthorizationKey: 'Autorisierungsprozess abgelehnt',
  yourResetPasswordHasExpired:
    'Ihre Passwortzurücksetzungssitzung ist abgelaufen. Bitte versuchen Sie es erneut',
  incorrectOldPassword: 'Das alte Passwort ist falsch',
  youMustProvideValidPasswordConfirmation:
    'Sie müssen das Passwort zur Bestätigung korrekt eingeben',
  ' ': ' ',
  Serwisy: 'Dienste',
  youHaveAlreadyVerifiedYourAccount: 'Sie haben Ihr Konto bereits verifiziert',
  userDoesNotExist: 'Benutzer existiert nicht',
  superAdmin: 'Superadministrator',
  admin: 'Administrator',
  user: 'Benutzer',
  'Czas aktywnej sesji (min)': 'Aktive Sitzungsdauer (Minuten)',
  login: 'Einloggen',
  welcome: 'Willkommen',
  'Devices Quantity': 'Gerätemenge',
  'Blocked Devices': 'Gesperrte Geräte',
  'Blocked IPs': 'Gesperrte IPs',
  userIsNotVerified: 'Benutzer ist nicht verifiziert',
  deviceVerified: 'Gerät wurde verifiziert',
  pleaseCheckYourEmailOrRetryAfter15minutes:
    'Bitte überprüfen Sie Ihre E-Mail oder versuchen Sie es in 15 Minuten erneut',
  deviceAlreadyBlocked: 'Gerät ist bereits gesperrt',
  ipAlreadyBlocked: 'IP ist bereits gesperrt',
  updatedUserCouldNotBeFound: 'Aktualisierter Benutzer konnte nicht gefunden werden',
  pleaseCheckYourEmailForResetPasswordOrRetryAfter15minutes:
    'Bitte überprüfen Sie Ihre E-Mail für die Passwortzurücksetzung oder versuchen Sie es in 15 Minuten erneut',
  verificationFailed: 'Verifizierung fehlgeschlagen',
  // Komunikaty
  rowHasBeenUpdated: 'Zeile wurde aktualisiert',
  setNewPassword: 'Neues Passwort festlegen',
  emailsAreEqual: 'E-Mails sind gleich',
  lastSignIn: 'Letzte Anmeldung',
  verifiedDevice: 'Gerät verifiziert',
  yourPasswordHasBeenSuccessfullyChanged: 'Ihr Passwort wurde erfolgreich geändert',
  visitMailBoxAndConfirmPasswordReset:
    'Besuchen Sie Ihr Postfach und bestätigen Sie die Passwortzurücksetzung',
  passwordChanged: 'Passwort geändert',
  passwordHasBeenChanged: 'Passwort wurde geändert',
  passwordHasBeenChangedDescription: 'Ihre Daten wurden geändert',
  confirmationEmailHasBeenSent: 'Bestätigungs-E-Mail wurde gesendet',

  // Ciągi
  _Auth: 'Manager',
  _orizationManager: 'Autorisierung',
  userCreated: 'Benutzer wurde erstellt',

  //25.05
  suppressSelfSecurityChanges: 'Die Möglichkeit zur Selbstbearbeitung der Sicherheitseinstellungen deaktivieren',
  suppressSelfSecurityChangesDescription:
    'Wenn diese Option aktiviert ist, kann der Benutzer seine Sicherheitseinstellungen nicht konfigurieren',
  verifyEmail: 'E-Mail verifizieren',
  _System:'HR-System',
  _Lombard:'Rekrutierung und Beschäftigung',
  employeesList:'Mitarbeiterliste',
  employeeSpecifications:'Mitarbeiterspezifikationen',
  employees:'Mitarbeiter',
  employeesDescription:'Mitarbeiterverzeichnis, Spezifikationen',
  specification:'Spezifikation',
  dateOfBirth:'Geburtsdatum',
  postcode:'Postleitzahl',
  userId:'Benutzer-ID',
  companies:'Unternehmen',
  housingAssistant:'Wohnungsassistent',
  recruiter:'E-Recruiter',
  documents:'Dokumente',
  integrations:'Integrationen',
  statistics:'Statistik'
};
